In [1]:
import pandas as pd

df = pd.read_excel('/home/ubuntu/cur/isep/v.5.2_result.xlsx', sheet_name='dan_vs_munic.')
df.head()

,Unnamed: 0,*CLAUSE_EXPLANATION,*CLAUSE_POSITIVE_PERMISSION_CONSENT,*CLAUSE_PENALTY_Lv2,*CLAUSE_PENALTY_Lv1,*CLAUSE_RESTRICTED_ZONE,*CLAUSE_ZONE_Lv1,*CLAUSE_ZONE_Lv2,*CLAUSE_ENVIRONMENT,*CLAUSE_DOC_REQUIREMENTS,...,*PROCEDURE_NOTICE_MUNICIPARITY,*PROCEDURE_CONSULTAION,*PROCEDURE_NOTICE_OPERATOR,*PROCEDURE_TIMING,*STAKEHOLDER_RESIDENTS,*CONFIRMATION,*STAKEHOLDER,*CLAUSE_STAKEHOLDER_CONFIRMATION,*GEO_REFERENCES,ケース数
0,えりも町,2 (1.40%),0 (0.00%),0 (0.00%),19 (13.29%),1 (0.70%),0 (0.00%),0 (0.00%),15 (10.49%),0 (0.00%),...,6 (4.20%),15 (10.49%),22 (15.38%),7 (4.90%),20 (13.99%),1 (0.70%),20 (13.99%),1 (0.70%),1 (0.70%),143
1,かすみがうら市,1 (0.81%),0 (0.00%),0 (0.00%),6 (4.88%),0 (0.00%),0 (0.00%),0 (0.00%),12 (9.76%),0 (0.00%),...,7 (5.69%),8 (6.50%),23 (18.70%),6 (4.88%),5 (4.07%),0 (0.00%),5 (4.07%),0 (0.00%),0 (0.00%),123
2,かつらぎ町,0 (0.00%),0 (0.00%),0 (0.00%),12 (12.24%),0 (0.00%),0 (0.00%),0 (0.00%),4 (4.08%),0 (0.00%),...,2 (2.04%),10 (10.20%),26 (26.53%),6 (6.12%),10 (10.20%),2 (2.04%),10 (10.20%),0 (0.00%),0 (0.00%),98
3,さくら市,10 (6.17%),6 (3.70%),0 (0.00%),19 (11.73%),0 (0.00%),7 (4.32%),0 (0.00%),17 (10.49%),3 (1.85%),...,6 (3.70%),0 (0.00%),32 (19.75%),1 (0.62%),9 (5.56%),0 (0.00%),9 (5.56%),0 (0.00%),3 (1.85%),162
4,つくば市,22 (12.43%),0 (0.00%),0 (0.00%),29 (16.38%),3 (1.69%),6 (3.39%),6 (3.39%),15 (8.47%),0 (0.00%),...,10 (5.65%),0 (0.00%),58 (32.77%),11 (6.21%),15 (8.47%),0 (0.00%),15 (8.47%),0 (0.00%),3 (1.69%),177

In [2]:
import re

# 個数とパーセンテージを分離する関数
def split_count_and_ratio(value):
    if pd.isna(value):
        return 0, 0.0
    
    # 文字列として処理
    value_str = str(value)
    
    # パターン: "個数 (パーセント%)"
    match = re.match(r'(\d+)\s*\((\d+\.?\d*)%\)', value_str)
    if match:
        count = int(match.group(1))
        ratio = float(match.group(2))
        return count, ratio
    else:
        # パースできない場合は元の値を返す
        return value, 0.0

# 'Unnamed: 0'と'ケース数'以外の列を処理
columns_to_process = [col for col in df.columns if col not in ['Unnamed: 0', 'ケース数']]

# 新しいデータフレームを作成
new_df = df[['Unnamed: 0']].copy()

for col in columns_to_process:
    # 個数とパーセンテージを分離
    counts, ratios = zip(*df[col].apply(split_count_and_ratio))
    
    # 個数の列
    new_df[col] = counts
    
    # パーセンテージの列(ratio)
    new_df[f'{col}_ratio(%)'] = ratios

# 最後に'ケース数'を追加
new_df['ケース数'] = df['ケース数']

# 結果を確認

new_df.to_csv("result2.2.csv")
new_df.head()

,Unnamed: 0,*CLAUSE_EXPLANATION,*CLAUSE_EXPLANATION_ratio(%),*CLAUSE_POSITIVE_PERMISSION_CONSENT,*CLAUSE_POSITIVE_PERMISSION_CONSENT_ratio(%),*CLAUSE_PENALTY_Lv2,*CLAUSE_PENALTY_Lv2_ratio(%),*CLAUSE_PENALTY_Lv1,*CLAUSE_PENALTY_Lv1_ratio(%),*CLAUSE_RESTRICTED_ZONE,...,*STAKEHOLDER_RESIDENTS_ratio(%),*CONFIRMATION,*CONFIRMATION_ratio(%),*STAKEHOLDER,*STAKEHOLDER_ratio(%),*CLAUSE_STAKEHOLDER_CONFIRMATION,*CLAUSE_STAKEHOLDER_CONFIRMATION_ratio(%),*GEO_REFERENCES,*GEO_REFERENCES_ratio(%),ケース数
0,えりも町,2,1.40,0,0.0,0,0.0,19,13.29,1,...,13.99,1,0.70,20,13.99,1,0.7,1,0.70,143
1,かすみがうら市,1,0.81,0,0.0,0,0.0,6,4.88,0,...,4.07,0,0.00,5,4.07,0,0.0,0,0.00,123
2,かつらぎ町,0,0.00,0,0.0,0,0.0,12,12.24,0,...,10.20,2,2.04,10,10.20,0,0.0,0,0.00,98
3,さくら市,10,6.17,6,3.7,0,0.0,19,11.73,0,...,5.56,0,0.00,9,5.56,0,0.0,3,1.85,162
4,つくば市,22,12.43,0,0.0,0,0.0,29,16.38,3,...,8.47,0,0.00,15,8.47,0,0.0,3,1.69,177

(旧) 住民同意フラグ付与セル — 後続に移動しました。

# ピアソン残差の計算と分析

## 1. データの前処理

合計行とカイ2乗値行を除外し、ピアソン残差を計算します。

In [16]:
import numpy as np
from scipy.stats import chi2_contingency

# 合計行とカイ2乗値行を除外(最後の2行)
df_analysis = new_df.iloc[:-2].copy()

# 数値列を数値型に変換(自治体名以外)
numeric_columns = [col for col in df_analysis.columns if col != 'Unnamed: 0']
for col in numeric_columns:
    df_analysis[col] = pd.to_numeric(df_analysis[col], errors='coerce').fillna(0)

# カウント列は整数型に(比率列以外)
count_columns = [col for col in numeric_columns if '_ratio(%)' not in col and col != 'ケース数']
for col in count_columns:
    df_analysis[col] = df_analysis[col].astype(int)

# ケース数も整数型に
df_analysis['ケース数'] = df_analysis['ケース数'].astype(int)

# 自治体名列を確認
print("分析対象自治体数:", len(df_analysis))
print("\n最初の5自治体:")
print(df_analysis['Unnamed: 0'].head())

# データ型を確認
print("\nデータ型(最初の10列):")
print(df_analysis.dtypes.head(100))

分析対象自治体数: 315

最初の5自治体:
0       えりも町
1    かすみがうら市
2      かつらぎ町
3       さくら市
4       つくば市
Name: Unnamed: 0, dtype: object

データ型(最初の10列):
Unnamed: 0                                       object
*CLAUSE_EXPLANATION                               int64
*CLAUSE_EXPLANATION_ratio(%)                    float64
*CLAUSE_POSITIVE_PERMISSION_CONSENT               int64
*CLAUSE_POSITIVE_PERMISSION_CONSENT_ratio(%)    float64
*CLAUSE_PENALTY_Lv2                               int64
*CLAUSE_PENALTY_Lv2_ratio(%)                    float64
*CLAUSE_PENALTY_Lv1                               int64
*CLAUSE_PENALTY_Lv1_ratio(%)                    float64
*CLAUSE_RESTRICTED_ZONE                           int64
*CLAUSE_RESTRICTED_ZONE_ratio(%)                float64
*CLAUSE_ZONE_Lv1                                  int64
*CLAUSE_ZONE_Lv1_ratio(%)                       float64
*CLAUSE_ZONE_Lv2                                  int64
*CLAUSE_ZONE_Lv2_ratio(%)                       float64
*CLAUSE_ENVIRONMENT                               int64
*CLAUSE_ENVIRONMENT_ratio(%)                    float64
*CLAUSE_DOC_REQUIREMENTS                          int64
*CLAUSE_DOC_REQUIREMENTS_ratio(%)               float64
*CLAUSE_DECOMMISSION_MAINTENANCE                  int64
*CLAUSE_DECOMMISSION_MAINTENANCE_ratio(%)       float64
*CLAUSE_SIGNAGE                                   int64
*CLAUSE_SIGNAGE_ratio(%)                        float64
*CLAUSE_PUBLICITY                                 int64
*CLAUSE_PUBLICITY_ratio(%)                      float64
*CLAUSE_HEARING                                   int64
*CLAUSE_HEARING_ratio(%)                        float64
*CLAUSE_FINANCE                                   int64
*CLAUSE_FINANCE_ratio(%)                        float64
*CLAUSE_EQUIPMENT_NOISE                           int64
*CLAUSE_EQUIPMENT_NOISE_ratio(%)                float64
*MODAL_PROHIBIT                                   int64
*MODAL_PROHIBIT_ratio(%)                        float64
*MODAL_MUST                                       int64
*MODAL_MUST_ratio(%)                            float64
*MODAL_SHOULD                                     int64
*MODAL_SHOULD_ratio(%)                          float64
*GUARD_EXCEPTION_TADASHI                          int64
*GUARD_EXCEPTION_TADASHI_ratio(%)               float64
*PROCEDURE_NOTICE_MUNICIPARITY                    int64
*PROCEDURE_NOTICE_MUNICIPARITY_ratio(%)         float64
*PROCEDURE_CONSULTAION                            int64
*PROCEDURE_CONSULTAION_ratio(%)                 float64
*PROCEDURE_NOTICE_OPERATOR                        int64
*PROCEDURE_NOTICE_OPERATOR_ratio(%)             float64
*PROCEDURE_TIMING                                 int64
*PROCEDURE_TIMING_ratio(%)                      float64
*STAKEHOLDER_RESIDENTS                            int64
*STAKEHOLDER_RESIDENTS_ratio(%)                 float64
*CONFIRMATION                                     int64
*CONFIRMATION_ratio(%)                          float64
*STAKEHOLDER                                      int64
*STAKEHOLDER_ratio(%)                           float64
*CLAUSE_STAKEHOLDER_CONFIRMATION                  int64
*CLAUSE_STAKEHOLDER_CONFIRMATION_ratio(%)       float64
*GEO_REFERENCES                                   int64
*GEO_REFERENCES_ratio(%)                        float64
ケース数                                              int64
dtype: object

In [4]:
# ピアソン残差を計算する関数
def calculate_pearson_residuals(df_data):
    """
    各コーディング項目についてピアソン残差を計算
    
    Parameters:
    -----------
    df_data : DataFrame
        自治体×コーディング項目のカウントデータ
    
    Returns:
    --------
    df_with_residuals : DataFrame
        ピアソン残差列を追加したデータフレーム
    """
    # 結果を格納するデータフレーム
    df_result = df_data.copy()
    
    # カウント列のみを抽出(比率列とケース数は除外)
    count_columns = [col for col in df_data.columns 
                     if col not in ['Unnamed: 0', 'ケース数'] 
                     and '_ratio(%)' not in col]
    
    # 各カウント列についてピアソン残差を計算
    for col in count_columns:
        # クロス集計表を作成(自治体 × 当該コーディングの有無)
        # 各自治体の当該コーディング出現回数と非出現回数
        present = df_data[col].values
        total_cases = df_data['ケース数'].values
        absent = total_cases - present
        
        # クロス集計表
        contingency_table = np.column_stack([present, absent])
        
        # カイ2乗検定
        try:
            chi2, p_value, dof, expected = chi2_contingency(contingency_table)
            
            # ピアソン残差を計算: (観測度数 - 期待度数) / sqrt(期待度数)
            pearson_resid = (present - expected[:, 0]) / np.sqrt(expected[:, 0])
            
            # 残差列を追加
            df_result[f'{col}_pearson_resid'] = pearson_resid
            
        except Exception as e:
            print(f"警告: {col} の計算中にエラー: {e}")
            df_result[f'{col}_pearson_resid'] = 0.0
    
    return df_result

# ピアソン残差を計算
print("ピアソン残差を計算中...")
df_with_residuals = calculate_pearson_residuals(df_analysis)

print(f"\n計算完了。列数: {len(df_with_residuals.columns)}")
print("\n追加された残差列の例:")
residual_cols = [col for col in df_with_residuals.columns if 'pearson_resid' in col]
print(residual_cols[:5])

ピアソン残差を計算中...

計算完了。列数: 86

追加された残差列の例:
['*CLAUSE_EXPLANATION_pearson_resid', '*CLAUSE_POSITIVE_PERMISSION_CONSENT_pearson_resid', '*CLAUSE_PENALTY_Lv2_pearson_resid', '*CLAUSE_PENALTY_Lv1_pearson_resid', '*CLAUSE_RESTRICTED_ZONE_pearson_resid']

In [5]:
# 自治体名列をわかりやすい名前に変更
df_with_residuals = df_with_residuals.rename(columns={'Unnamed: 0': 'Municiparity_name'})

# 結果を確認
print("データの形状:", df_with_residuals.shape)
print("\n最初の3自治体のデータ(抜粋):")
display_cols = ['Municiparity_name', 
                '*CLAUSE_POSITIVE_PERMISSION_CONSENT',
                '*CLAUSE_POSITIVE_PERMISSION_CONSENT_pearson_resid',
                '*CLAUSE_ZONE_Lv1',
                '*CLAUSE_ZONE_Lv1_pearson_resid',
                '*CLAUSE_ZONE_Lv2',
                '*CLAUSE_ZONE_Lv2_pearson_resid',
                'ケース数']

df_with_residuals[display_cols].head(3)

データの形状: (315, 86)

最初の3自治体のデータ(抜粋):

,Municiparity_name,*CLAUSE_POSITIVE_PERMISSION_CONSENT,*CLAUSE_POSITIVE_PERMISSION_CONSENT_pearson_resid,*CLAUSE_ZONE_Lv1,*CLAUSE_ZONE_Lv1_pearson_resid,*CLAUSE_ZONE_Lv2,*CLAUSE_ZONE_Lv2_pearson_resid,ケース数
0,えりも町,0,-1.679267,0,-2.273739,0,-1.066618,143
1,かすみがうら市,0,-1.557415,0,-2.108750,0,-0.989221,123
2,かつらぎ町,0,-1.390160,0,-1.882286,0,-0.882986,98

In [6]:
# ピアソン残差の統計情報
residual_cols = [col for col in df_with_residuals.columns if 'pearson_resid' in col]

print("ピアソン残差の統計情報:")
print(df_with_residuals[residual_cols].describe())

# 顕著な正の残差(>1.0)を持つ項目を確認
print("\n\n顕著な正の残差(>1.0)を持つケース数:")
for col in residual_cols:
    count = (df_with_residuals[col] > 1.0).sum()
    if count > 0:
        print(f"{col}: {count}件")

ピアソン残差の統計情報:
       *CLAUSE_EXPLANATION_pearson_resid  \
count                         315.000000
mean                            0.077186
std                             1.292254
min                            -3.807984
25%                            -0.801646
50%                             0.080420
75%                             0.710856
max                             5.003856

       *CLAUSE_POSITIVE_PERMISSION_CONSENT_pearson_resid  \
count                                         315.000000
mean                                           -0.024433
std                                             1.963422
min                                            -2.719365
25%                                            -1.472815
50%                                            -1.041437
75%                                             1.130957
max                                             6.698329

       *CLAUSE_PENALTY_Lv2_pearson_resid  *CLAUSE_PENALTY_Lv1_pearson_resid  \
count                         315.000000                         315.000000
mean                            0.022771                           0.115118
std                             1.829520                           1.273382
min                            -0.783699                          -3.384288
25%                            -0.471132                          -0.761867
50%                            -0.414541                           0.094283
75%                            -0.330140                           0.987685
max                            12.471545                           4.337182

       *CLAUSE_RESTRICTED_ZONE_pearson_resid  *CLAUSE_ZONE_Lv1_pearson_resid  \
count                             315.000000                      315.000000
mean                               -0.012419                        0.039881
std                                 1.085439                        1.812764
min                                -1.174778                       -3.415716
25%                                -0.684766                       -1.557577
50%                                -0.550499                        0.049952
75%                                 0.678063                        1.318956
max                                 4.952156                        5.125673

       *CLAUSE_ZONE_Lv2_pearson_resid  *CLAUSE_ENVIRONMENT_pearson_resid  \
count                      315.000000                         315.000000
mean                        -0.007114                           0.047273
std                          1.891712                           1.772948
min                         -1.752405                          -5.310069
25%                         -0.989221                          -0.946257
50%                         -0.802756                          -0.073284
75%                          0.071700                           0.918379
max                          8.987091                           6.360091

       *CLAUSE_DOC_REQUIREMENTS_pearson_resid  \
count                              315.000000
mean                                 0.008356
std                                  1.573417
min                                 -2.331233
25%                                 -1.234920
50%                                 -0.331785
75%                                  0.839799
max                                  5.383565

       *CLAUSE_DECOMMISSION_MAINTENANCE_pearson_resid  ...  \
count                                      315.000000  ...
mean                                         0.012304  ...
std                                          1.803367  ...
min                                         -3.327492  ...
25%                                         -1.401666  ...
50%                                         -0.085368  ...
75%                                          1.016686  ...
max                                          8.464999  ...

       *GUARD_EXCEPTION_TADASHI_pearson_resid  \
count                              315.000000
mean                                 0.002438
std                                  1.015623
min                                 -0.100342
25%                                 -0.061500
50%                                 -0.053809
75%                                 -0.045106
max                                 17.969221

       *PROCEDURE_NOTICE_MUNICIPARITY_pearson_resid  \
count                                    315.000000
mean                                       0.105067
std                                        1.593812
min                                       -4.279286
25%                                       -1.031429
50%                                        0.096877
75%                                        1.149319
max                                        4.470816

       *PROCEDURE_CONSULTAION_pearson_resid  \
count                            315.000000
mean                               0.073241
std                                2.201260
min                               -5.504195
25%                               -1.578729
50%                               -0.024805
75%                                1.390199
max                                8.782401

       *PROCEDURE_NOTICE_OPERATOR_pearson_resid  \
count                                315.000000
mean                                   0.185919
std                                    1.876458
min                                   -6.400738
25%                                   -0.931759
50%                                    0.206895
75%                                    1.478984
max                                    4.530839

       *PROCEDURE_TIMING_pearson_resid  *STAKEHOLDER_RESIDENTS_pearson_resid  \
count                       315.000000                            315.000000
mean                          0.055742                              0.050445
std                           1.739051                              1.859495
min                          -4.225332                             -4.997660
25%                          -1.222926                             -1.365946
50%                          -0.209194                              0.220651
75%                           1.000685                              1.248657
max                           7.427316                              5.711350

       *CONFIRMATION_pearson_resid  *STAKEHOLDER_pearson_resid  \
count                   315.000000                  315.000000
mean                      0.090798                    0.069368
std                       1.840035                    1.759976
min                      -2.077357                   -4.748077
25%                      -1.153831                   -1.268228
50%                      -0.801699                    0.190093
75%                       1.027177                    1.146639
max                       9.293887                    5.386505

       *CLAUSE_STAKEHOLDER_CONFIRMATION_pearson_resid  \
count                                      315.000000
mean                                         0.036374
std                                          1.405849
min                                         -1.066630
25%                                         -0.643843
50%                                         -0.538959
75%                                         -0.381081
max                                          6.841604

       *GEO_REFERENCES_pearson_resid
count                     315.000000
mean                       -0.070488
std                         1.309336
min                        -1.912667
25%                        -1.001069
50%                        -0.662147
75%                         0.462224
max                         6.653305

[8 rows x 28 columns]


顕著な正の残差(>1.0)を持つケース数:
*CLAUSE_EXPLANATION_pearson_resid: 60件
*CLAUSE_POSITIVE_PERMISSION_CONSENT_pearson_resid: 86件
*CLAUSE_PENALTY_Lv2_pearson_resid: 22件
*CLAUSE_PENALTY_Lv1_pearson_resid: 78件
*CLAUSE_RESTRICTED_ZONE_pearson_resid: 51件
*CLAUSE_ZONE_Lv1_pearson_resid: 99件
*CLAUSE_ZONE_Lv2_pearson_resid: 62件
*CLAUSE_ENVIRONMENT_pearson_resid: 73件
*CLAUSE_DOC_REQUIREMENTS_pearson_resid: 68件
*CLAUSE_DECOMMISSION_MAINTENANCE_pearson_resid: 81件
*CLAUSE_SIGNAGE_pearson_resid: 76件
*CLAUSE_PUBLICITY_pearson_resid: 46件
*CLAUSE_HEARING_pearson_resid: 33件
*CLAUSE_FINANCE_pearson_resid: 21件
*CLAUSE_EQUIPMENT_NOISE_pearson_resid: 48件
*MODAL_PROHIBIT_pearson_resid: 47件
*MODAL_MUST_pearson_resid: 91件
*MODAL_SHOULD_pearson_resid: 83件
*GUARD_EXCEPTION_TADASHI_pearson_resid: 1件
*PROCEDURE_NOTICE_MUNICIPARITY_pearson_resid: 95件
*PROCEDURE_CONSULTAION_pearson_resid: 102件
*PROCEDURE_NOTICE_OPERATOR_pearson_resid: 110件
*PROCEDURE_TIMING_pearson_resid: 79件
*STAKEHOLDER_RESIDENTS_pearson_resid: 99件
*CONFIRMATION_pearson_resid: 79件
*STAKEHOLDER_pearson_resid: 92件
*CLAUSE_STAKEHOLDER_CONFIRMATION_pearson_resid: 57件
*GEO_REFERENCES_pearson_resid: 54件

In [7]:
# CSVファイルとして保存(ピアソン残差込み)
output_path = '/home/ubuntu/cur/isep/result_solar_rule_gof_tests.csv'
df_with_residuals.to_csv(output_path, index=False, encoding='utf-8-sig')
print(f"ピアソン残差を含むデータを保存しました: {output_path}")

ピアソン残差を含むデータを保存しました: /home/ubuntu/cur/isep/result_solar_rule_gof_tests.csv

## 2. 許可制 vs 届出制の判定

`CLAUSE_POSITIVE_PERMISSION_CONSENT`(許可・承認)と`PROCEDURE_NOTICE_OPERATOR`(届出)の出現頻度とPearson残差を組み合わせて、各自治体の規制タイプを判定します。

**判定基準:**
- **Pearson残差を考慮**: 残差が正(+1.0以上)の場合、その条項が自治体で特徴的に重視されていると判断
- **許可制優位**: 
  - 許可のPearson残差 > 1.0、または
  - 許可 > 0 かつ (届出 = 0 または 許可/届出 ≥ 0.5)
- **届出制優位**: 
  - 届出のPearson残差 > 1.0 かつ 許可のPearson残差 < 1.0、または
  - 許可 = 0 かつ 届出 > 0
- **混合型**: 上記以外

In [8]:
def classify_regulation_type(row):
    """許可制・届出制の分類関数
    
    法律文書では「許可」という文言は慎重に使用されるため、
    出現回数とPearson残差を組み合わせて判定する。
    """
    permission = row['*CLAUSE_POSITIVE_PERMISSION_CONSENT']
    notice = row['*PROCEDURE_NOTICE_OPERATOR']
    permission_resid = row['*CLAUSE_POSITIVE_PERMISSION_CONSENT_pearson_resid']
    notice_resid = row['*PROCEDURE_NOTICE_OPERATOR_pearson_resid']
    
    # 両方とも0の場合
    if notice == 0 and permission == 0:
        return '規定なし'
    
    # Pearson残差が大きい(+1.0以上)場合、その条項が特徴的に重視されている
    # 許可のPearson残差が顕著に正の場合、許可制優位
    if permission_resid > 1.0:
        return '許可制優位'
    
    # 届出のPearson残差が顕著に正で、許可が特徴的でない場合、届出制優位
    if notice_resid > 1.0 and permission_resid < 1.0:
        return '届出制優位'
    
    # Pearson残差が決定的でない場合、カウント数で判定
    if permission > 0:
        if notice == 0:
            return '許可制優位'
        ratio = permission / notice
        # 許可が届出の半分以上あれば、許可制の意図があると判断
        if ratio >= 0.5:
            return '許可制優位'
        else:
            return '許可制優位'
    else:
        # 許可が0で届出のみの場合
        return '届出制優位'

# 分類の適用
df_with_residuals['規制タイプ'] = df_with_residuals.apply(classify_regulation_type, axis=1)

# 結果の表示
regulation_summary = df_with_residuals[['Municiparity_name', 
                                '*CLAUSE_POSITIVE_PERMISSION_CONSENT',
                                '*CLAUSE_POSITIVE_PERMISSION_CONSENT_pearson_resid',
                                '*PROCEDURE_NOTICE_OPERATOR',
                                '*PROCEDURE_NOTICE_OPERATOR_pearson_resid',
                                '規制タイプ']].copy()
regulation_summary.columns = ['自治体', '許可関連', '許可(残差)', '届出関連', '届出(残差)', '規制タイプ']
# 残差を小数点第2位まで表示
regulation_summary['許可(残差)'] = regulation_summary['許可(残差)'].round(2)
regulation_summary['届出(残差)'] = regulation_summary['届出(残差)'].round(2)
print(regulation_summary.to_string(index=False))

print("\n\n規制タイプの分布:")
print(df_with_residuals['規制タイプ'].value_counts())

     自治体  許可関連  許可(残差)  届出関連  届出(残差) 規制タイプ
    えりも町     0   -1.68    22   -1.80 届出制優位
 かすみがうら市     0   -1.56    23   -0.89 届出制優位
   かつらぎ町     0   -1.39    26    0.84 届出制優位
    さくら市     6    1.57    32   -0.74 許可制優位
    つくば市     0   -1.87    58    2.88 届出制優位
   ときがわ町     0   -1.69    50    3.09 届出制優位
    みどり市     9    2.14    24   -3.79 許可制優位
   みなかみ町     6    2.21    30    0.27 許可制優位
    みやこ町     0   -1.32    23    0.72 届出制優位
    ニセコ町     0   -1.49    35    1.90 届出制優位
     阿智村     9    4.41    22   -0.84 許可制優位
     愛南町     1   -0.57    16   -0.90 許可制優位
  愛媛県上島町     4    2.17    16   -0.05 許可制優位
      綾町     5    1.63    25   -0.55 許可制優位
     安中市     3    1.23    19    0.46 許可制優位
    安曇野市     5    1.07    19   -2.78 許可制優位
     安平町     0   -1.38    21   -0.18 届出制優位
     伊達市     7    2.79    42    2.41 許可制優位
     伊東市     2   -0.20    15   -2.21 許可制優位
   伊豆の国市     2    0.83    19    1.72 届出制優位
     伊豆市     3    0.31    26   -0.48 許可制優位
     伊那市     6    3.76     8   -2.12 許可制優位
     伊方町     3    0.94    22    0.44 許可制優位
    伊万里市     3    1.67    17    0.95 許可制優位
  茨城県守谷市     0   -1.13    21    1.67 届出制優位
茨城県常陸太田市     3    0.88    30    2.04 届出制優位
     茨城町     0   -1.14    19    1.08 届出制優位
     宇佐市     0   -1.25    19    0.29 届出制優位
     宇治市     6    4.12    19    1.08 許可制優位
     宇陀市     0   -1.47    30    1.10 届出制優位
    宇都宮市     8    1.84    45   -0.46 許可制優位
    宇和島市     9    1.67    23   -4.70 許可制優位
     羽幌町     0   -2.49    17   -6.40 届出制優位
     益子町     0   -1.96    33   -1.64 届出制優位
     越生町     0   -1.90    41   -0.06 届出制優位
     遠野市     4    1.32    17   -1.40 許可制優位
     塩尻市     0   -1.75    47    2.05 届出制優位
     塩谷町    14    3.74    56   -0.64 許可制優位
     岡垣町     0   -1.34    32    2.55 届出制優位
  岡山県美作市     0   -0.98    16    1.50 届出制優位
     下関市     0   -1.77    36    0.04 届出制優位
     下妻市     0   -1.97    41   -0.50 届出制優位
     下田市     4    1.11    26   -0.06 許可制優位
     加美町     0   -1.73    26   -1.40 届出制優位
     可児市     0   -1.81    34   -0.58 届出制優位
    我孫子市     0   -0.88    13    1.43 届出制優位
     皆野町     4    0.18    48    0.99 許可制優位
     角田市     5    1.84    23   -0.52 許可制優位
     掛川市     3    0.43    19   -1.50 許可制優位
     笠間市     0   -1.29    17   -0.44 届出制優位
     滑川町     0   -1.72    44    1.76 届出制優位
      関市     0   -1.29    24    1.17 届出制優位
     丸森町     2   -0.47    31   -0.13 許可制優位
     岩国市     0   -1.56    28    0.06 届出制優位
     嬉野市     0   -1.95    52    1.30 届出制優位
     寄居町     0   -1.32    37    3.86 届出制優位
    紀美野町     0   -1.65    24   -1.27 届出制優位
     鬼北町     5    1.97    14   -2.09 許可制優位
     亀岡市     4    2.10    12   -1.14 許可制優位
     菊川市     2    0.06    24    0.46 許可制優位
     菊池市     9    2.00    30   -3.20 許可制優位
     吉岡町     7    3.58    24    0.31 許可制優位
     吉賀町     2   -0.18    16   -1.94 許可制優位
     吉見町     1   -1.04    38    1.29 届出制優位
     宮古市     1   -1.86    31   -3.75 許可制優位
     牛久市     0   -1.47    21   -0.71 届出制優位
    京丹後市     0   -1.05    16    0.96 届出制優位
    京丹波町     0   -1.98    34   -1.58 届出制優位
    京田辺市    12    4.22    37   -0.94 許可制優位
     喬木村     8    4.67    10   -2.28 許可制優位
      境町     0   -1.23    19    0.40 届出制優位
     橋本市     0   -0.96    14    1.05 届出制優位
     鏡野町     0   -1.04    24    3.30 届出制優位
     玉川村     3    0.68    32    1.83 届出制優位
     桐生市    20    6.70    36   -2.80 許可制優位
 桐生市_改正前     5    0.59    12   -4.81 許可制優位
      錦町     0   -1.53    36    1.83 届出制優位
     金沢市     4    1.44    32    2.00 許可制優位
     串本町     0   -1.59    25   -0.75 届出制優位
     釧路市     7    1.86    50    1.57 許可制優位
     熊取町     0   -1.06    21    2.28 届出制優位
     熊谷市     0   -1.65    45    2.50 届出制優位
     栗原市     0   -1.12    13   -0.37 届出制優位
     恵那市     3   -0.59    42   -0.89 許可制優位
     結城市     0   -1.51    29    0.61 届出制優位
     月形町     0   -1.36    32    2.36 届出制優位
      原村     0   -1.07    14    0.26 届出制優位
     古河市     0   -1.13    23    2.19 届出制優位
    古座川町     0   -1.42    21   -0.41 届出制優位
     古平町     6    2.78    31    1.62 許可制優位
     湖西市     3    1.23    26    2.15 許可制優位
     五霞町     0   -1.10    27    3.58 届出制優位
     五條市     0   -1.40    19   -0.70 届出制優位
     御宿町     2   -0.21    26   -0.11 許可制優位
     御所市     0   -1.67    28   -0.66 届出制優位
     御嵩町     0   -1.09    22    2.31 届出制優位
    御前崎市     3    1.07    16   -0.62 許可制優位
     厚真町     0   -0.99    12    0.22 届出制優位
     江差町     0   -1.49    35    1.95 届出制優位
     高崎市    10    3.88    22   -2.30 許可制優位
     高山村    13    3.43    48   -1.45 許可制優位
     高取町     0   -1.10    16    0.61 届出制優位
  高知県須崎市     4    2.67     5   -2.23 許可制優位
     高槻市     0   -1.43    29    1.16 届出制優位
     国見町     5    1.90    29    0.80 許可制優位
     今金町     2    0.32    20    0.41 許可制優位
    佐久穂町     2   -0.47    31   -0.13 許可制優位
     佐伯市     0   -1.42    29    1.26 届出制優位
     佐野市    10    3.12    34   -1.52 許可制優位
     坂東市     0   -1.20    22    1.37 届出制優位
     桜井市     0   -1.43    19   -0.91 届出制優位
     三郷町     5    3.08    13   -0.69 許可制優位
     三木市     0   -1.07    28    4.14 届出制優位
     山形村     0   -1.53    21   -1.08 届出制優位
     山元町     0   -1.32    15   -1.12 届出制優位
     士別市     0   -1.75    56    3.53 届出制優位
     市川町     0   -1.29    34    3.40 届出制優位
     志摩市     0   -1.33    27    1.50 届出制優位
     鹿沼市    15    5.81    28   -2.26 許可制優位
     鹿島市     8    3.53    48    3.75 許可制優位
     鹿嶋市     3    0.71    21   -0.36 許可制優位
     宍粟市     0   -1.70    41    1.42 届出制優位
     雫石町     1   -1.05    39    1.38 届出制優位
    七ヶ宿町     0   -1.12    21    1.74 届出制優位
     柴田町     0   -1.47    25    0.09 届出制優位
     斜里町     0   -1.35    28    1.55 届出制優位
     渋川市    10    5.00    19   -1.50 許可制優位
     宿毛市     0   -0.66     3   -0.88 届出制優位
     女川町     0   -1.45    23   -0.18 届出制優位
     小海町     6    2.32    18   -1.80 許可制優位
     小諸市     2    0.32    13   -1.22 許可制優位
     小川町     0   -1.50    42    3.23 届出制優位
     松江市     3   -0.16    43    0.88 許可制優位
     松崎町     3    0.61    26    0.39 許可制優位
     松田町     4    0.79    23   -1.41 許可制優位
     松本市    10    3.97    50    2.56 許可制優位
     沼津市     5    1.19    31   -0.47 許可制優位
     焼津市     3    1.25    13   -0.94 許可制優位
     上田市     0   -1.64    37    1.11 届出制優位
   常陸大宮市    12    4.14    52    1.19 許可制優位
     色麻町     0   -1.50    21   -0.92 届出制優位
     信濃町     0   -1.20    15   -0.35 届出制優位
     新宮市     0   -1.44    21   -0.54 届出制優位
     新城市     0   -1.19    34    4.42 届出制優位
     新得町     0   -1.43    24    0.12 届出制優位
     新富町     2    0.85    15    0.68 許可制優位
     真岡市     0   -1.73    35    0.14 届出制優位
     真庭市     1   -0.19    14    0.07 許可制優位
     神戸市    10    4.02    54    3.33 許可制優位
     諏訪市     0   -0.87    11    0.84 届出制優位
     須崎市     6    1.89    16   -2.85 許可制優位
     瑞浪市     0   -1.53    29    0.43 届出制優位
     裾野市     3    0.94    15   -1.12 許可制優位
     瀬戸市     2    0.09    30    1.86 届出制優位
     生坂村     3    0.31    17   -2.17 許可制優位
     西郷村     0   -0.92     3   -2.15 届出制優位
     西桂町     0   -1.47    38    2.66 届出制優位
 西桂町_改正前     0   -1.39    14   -1.72 届出制優位
     西予市     3    0.25    28   -0.31 許可制優位
     西脇市     0   -1.41    37    2.99 届出制優位
     青木村     0   -1.43    40    3.43 届出制優位
 静岡県西伊豆町     4    2.47    19    1.28 許可制優位
 静岡県東伊豆町     4    1.99    22    1.06 許可制優位
     石岡市     0   -1.11    11   -0.84 届出制優位
     石巻市     0   -1.50    23   -0.52 届出制優位
     赤磐市     0   -1.26    14   -0.99 届出制優位
     赤穂市     0   -1.50    12   -2.70 届出制優位
     仙台市     7    0.65    55   -0.96 許可制優位
  千葉県長柄町     0   -0.77    10    1.25 届出制優位
     川崎町     0   -2.00    36   -1.40 届出制優位
     川島町     0   -1.89    56    2.35 届出制優位
     川俣町     3    1.74    20    1.92 許可制優位
     前橋市    10    4.86    18   -1.84 許可制優位
     蔵王町     4    0.49    47    1.87 届出制優位
     足利市    13    3.83    41   -1.72 許可制優位
     村田町     0   -1.38    30    1.75 届出制優位
     多可町     0   -1.97    50    0.85 届出制優位
     太田市    10    3.16    24   -2.98 許可制優位
     袋井市     6   -0.06    58   -1.46 許可制優位
    大宜味村     0   -1.10    17    0.88 届出制優位
     大玉村     1   -0.12    18    1.44 届出制優位
     大空町     0   -1.46    28    0.75 届出制優位
     大桑村     2   -0.57    18   -2.74 許可制優位
     大崎市     0   -2.16    43   -1.42 届出制優位
     大子町     2    0.39    21    0.88 許可制優位
     大洲市     0   -1.38    36    3.10 届出制優位
     大町市     7    1.93    25   -2.26 許可制優位
     大町町     0   -1.22    25    1.98 届出制優位
     大津市     4    1.11    13   -2.60 許可制優位
     大津町     0   -1.65    41    1.78 届出制優位
    大田原市     8    2.20    46    0.50 許可制優位
     大府市     0   -1.45    23   -0.18 届出制優位
   大網白里市     0   -1.43    11   -2.53 届出制優位
     辰野町     3    0.98    17   -0.58 許可制優位
     丹波市     0   -1.38    43    4.53 届出制優位
     竹田市     0   -0.66     8    1.37 届出制優位
     秩父市     4    1.26    35    2.11 許可制優位
     中川村     0   -1.58    39    1.95 届出制優位
    中津川市     0   -1.53    35    1.59 届出制優位
     朝日村     0   -1.03    11   -0.33 届出制優位
     長沼町     0   -1.63    35    0.88 届出制優位
  長野県松川村     5    1.00    18   -3.08 許可制優位
  長野県筑北村     0   -1.47    26    0.30 届出制優位
     長野市     0   -2.21    52   -0.48 届出制優位
     鳥羽市     0   -1.16    15   -0.08 届出制優位
     鶴居村     0   -1.47    27    0.45 届出制優位
     天草市     0   -0.92    13    1.07 届出制優位
     天理市     0   -2.58    37   -4.46 届出制優位
     田川市     0   -1.04     9   -0.96 届出制優位
     田村市     0   -1.48    19   -1.20 届出制優位
     登米市     5    2.93    24    1.80 許可制優位
     登別市     0   -1.65    36    0.89 届出制優位
     砥部町     5    1.11    21   -2.35 許可制優位
     土佐市     0   -1.74    25   -1.64 届出制優位
   土佐清水市     0   -1.24     9   -2.04 届出制優位
     島田市     2    0.75    25    3.13 届出制優位
     東栄町     0   -1.37    20   -0.30 届出制優位
     東海村     0   -1.52    26   -0.06 届出制優位
    東広島市     0   -1.13    29    3.76 届出制優位
    東松山市     0   -1.61    49    3.59 届出制優位
      東村     0   -1.52    23   -0.65 届出制優位
    湯河原町     4    0.33    37   -0.27 許可制優位
     藤枝市     3    1.74    16    0.82 許可制優位
    苫小牧市     0   -1.49    34    1.75 届出制優位
     奈義町     0   -1.12    15    0.16 届出制優位
     那珂市     0   -1.50    29    0.66 届出制優位
   那須塩原市     0   -1.65     8   -4.14 届出制優位
     那須町     6    2.43    33    1.30 許可制優位
   那智勝浦町     0   -1.49    22   -0.68 届出制優位
     内子町     3    1.67    19    1.50 許可制優位
     楢葉町     0   -2.31    45   -2.02 届出制優位
    南伊勢町     0   -1.85    42    0.45 届出制優位
     南関町     5    1.88    22   -0.64 許可制優位
    南三陸町     0   -0.81     6   -0.52 届出制優位
    南山城村     8    2.65    22   -2.45 許可制優位
    南相馬市     6    2.63    26    0.30 許可制優位
     南丹市     0   -1.14    26    2.89 届出制優位
    南知多町     0   -1.74    40    0.95 届出制優位
     南砺市     5    1.02    15   -3.53 許可制優位
    南島原市    13    2.64    34   -4.52 許可制優位
    南箕輪村     0   -1.52    34    1.49 届出制優位
    南木曽町     0   -1.39    19   -0.65 届出制優位
     日光市    13    6.59    39    1.90 許可制優位
     日高市     2    0.08    21   -0.13 許可制優位
     日高町     0   -1.53    34    1.44 届出制優位
     日出町     0   -1.67    43    2.00 届出制優位
     日置市     0   -1.46    34    1.97 届出制優位
     日立市     0   -1.55    21   -1.23 届出制優位
     入間市     2    0.59    32    4.36 届出制優位
     熱海市     1   -0.92    29    0.21 許可制優位
     能勢町     5    1.04    32   -0.67 許可制優位
     売木村     0   -1.09    16    0.68 届出制優位
     白石市     4    0.61    34    0.04 許可制優位
     白馬村     3    1.41    16    0.12 許可制優位
     白老町     0   -1.56    46    3.48 届出制優位
     函南町     2    0.73    20    1.69 届出制優位
    八千代町     0   -1.62    38    1.47 届出制優位
     八幡市     0   -1.57    32    0.73 届出制優位
    八幡浜市     0   -1.66    35    0.66 届出制優位
    八幡平市     4    0.75    29   -0.45 許可制優位
     鳩山町     0   -1.60    48    3.47 届出制優位
     飯塚市     0   -1.56    37    1.72 届出制優位
     飯能市     0   -1.28    29    2.39 届出制優位
     飯豊町     2    1.15     8   -0.73 許可制優位
     磐田市     2    0.34    21    0.71 許可制優位
     備前市     0   -1.63    33    0.47 届出制優位
     美祢市     0   -0.93    14    1.30 届出制優位
     美浜町     0   -1.38    19   -0.61 届出制優位
     美里町     0   -1.73    26   -1.40 届出制優位
     標津町     0   -1.34    24    0.78 届出制優位
     浜松市     0   -1.07    28    4.14 届出制優位
     浜中町     0   -1.82    34   -0.62 届出制優位
     富岡市    10    3.23    25   -2.72 許可制優位
    富士宮市     1   -0.41    13   -0.99 許可制優位
    富士見町     9    5.81    19    0.13 許可制優位
     富谷市     0   -1.02    11   -0.27 届出制優位
     武雄市     2   -0.02    29    1.21 届出制優位
  福岡県直方市     0   -0.98     8   -0.91 届出制優位
     福島市     9    2.04    62    1.29 許可制優位
     平群町     5    2.93    11   -1.39 許可制優位
     平谷村     8    6.56     8   -1.30 許可制優位
     米原市     4   -1.25    46   -4.20 許可制優位
     芳賀町     8    2.43    44    0.70 許可制優位
     豊丘村     8    4.80    18   -0.36 許可制優位
     豊橋市     0   -1.37    32    2.30 届出制優位
     豊能町     5    1.38    31   -0.01 許可制優位
     鉾田市     0   -2.72    76   -0.91 届出制優位
     防府市     0   -1.45    21   -0.58 届出制優位
    北茨城市     0   -1.04    20    2.17 届出制優位
    北相木村     8    4.67    10   -2.28 許可制優位
     北斗市     6    2.27    40    2.29 許可制優位
     北杜市     6    2.78    15   -1.70 許可制優位
     本庄市     4    0.98    36    1.48 届出制優位
     麻績村     4    1.53    22    0.08 許可制優位
     箕面市     3    0.44     4   -4.38 許可制優位
      岬町     0   -1.07    22    2.48 届出制優位
     名張市     0   -1.00    20    2.52 届出制優位
     茂木町     8    2.20    46    0.50 許可制優位
    毛呂山町     0   -1.49    43    3.48 届出制優位
    木古内町     0   -1.40    28    1.16 届出制優位
     木曽町     4    0.40    35   -0.39 許可制優位
     木祖村     1   -0.31    13   -0.64 許可制優位
    木津川市     1   -0.69    23    0.10 許可制優位
     野田市    10    4.90    34    1.25 許可制優位
     野木町     0   -1.58    38    1.81 届出制優位
     矢祭町     9    3.61    20   -2.24 許可制優位
     矢吹町     3   -1.67    55   -3.42 許可制優位
     湧別町     1   -1.26    57    3.17 届出制優位
     由布市     0   -1.10    19    1.42 届出制優位
     羅臼町     0   -1.22    20    0.70 届出制優位
     嵐山町     0   -2.58    66   -1.13 届出制優位
     利根町     0   -1.56    20   -1.50 届出制優位
    龍ケ崎市     0   -1.17    19    0.82 届出制優位
    和歌山市     8    2.04    29   -2.39 許可制優位
     和気町     0   -1.88    47    1.06 届出制優位


規制タイプの分布:
規制タイプ
届出制優位    185
許可制優位    130
Name: count, dtype: int64

## 3. 区域設定の類型化

`CLAUSE_ZONE_Lv1`(抑制区域)と`CLAUSE_ZONE_Lv2`(禁止区域)の設定状況とPearson残差を組み合わせて、区域規制の類型を判定します。

**判定基準:**
- **Pearson残差を考慮**: 残差が正(+1.0以上)の場合、その区域設定が自治体で特徴的に重視されていると判断
- **禁止地区制**: 
  - 禁止区域のPearson残差 > 1.0、または
  - Lv2 > 0 かつ Lv1 < Lv2 × 2
- **抑制地区制**: 
  - 抑制区域のPearson残差 > 1.0 かつ 禁止区域のPearson残差 < 1.0、または
  - Lv2 = 0 かつ Lv1 ≥ 3
- **2層構造**: Lv1 ≥ 3 かつ Lv2 ≥ 3

In [9]:
# 禁止区域の程度を数値化する指標を追加
# 禁止区域比率 = Lv2 / (Lv1 + Lv2)
df_with_residuals['禁止区域比率'] = (
    df_with_residuals['*CLAUSE_ZONE_Lv2'] / 
    (df_with_residuals['*CLAUSE_ZONE_Lv1'] + df_with_residuals['*CLAUSE_ZONE_Lv2'])
).fillna(0)

# 正規化された禁止区域の強度(ケース数あたり)
df_with_residuals['禁止区域強度(正規化)'] = (
    df_with_residuals['*CLAUSE_ZONE_Lv2'] / df_with_residuals['ケース数'] * 100
)

print("禁止区域の程度を示す指標を追加しました:")
print("\n禁止区域比率の統計:")
print(df_with_residuals['禁止区域比率'].describe())
print("\n禁止区域強度(正規化)の統計:")
print(df_with_residuals['禁止区域強度(正規化)'].describe())

禁止区域の程度を示す指標を追加しました:

禁止区域比率の統計:
count    315.000000
mean       0.153786
std        0.296106
min        0.000000
25%        0.000000
50%        0.000000
75%        0.183333
max        1.000000
Name: 禁止区域比率, dtype: float64

禁止区域強度(正規化)の統計:
count    315.000000
mean       0.765982
std        1.537423
min        0.000000
25%        0.000000
50%        0.000000
75%        0.854701
max        8.000000
Name: 禁止区域強度(正規化), dtype: float64

In [10]:
def classify_zone_type(row):
    """区域設定の類型化関数
    
    法律文書では「禁止」という文言は慎重に使用されるため、
    出現回数とPearson残差を組み合わせて判定する。
    
    【変更点】'2層構造(禁止+抑制)'と'抑制地区制(禁止区域含む)'を統合し、
    '2層構造(抑制+禁止)'として分類。禁止区域の程度は別途「禁止区域比率」で保持。
    """
    lv1 = row['*CLAUSE_ZONE_Lv1']  # 抑制区域
    lv2 = row['*CLAUSE_ZONE_Lv2']  # 禁止区域
    lv1_resid = row['*CLAUSE_ZONE_Lv1_pearson_resid']
    lv2_resid = row['*CLAUSE_ZONE_Lv2_pearson_resid']
    
    # 両方とも0の場合
    if lv1 == 0 and lv2 == 0:
        return '区域設定なし'
    
    # Pearson残差が大きい(+1.0以上)場合、その区域設定が特徴的に重視されている
    # 禁止区域のPearson残差が顕著に正の場合、禁止地区制
    if lv2_resid > 1.0:
        # ただし、両方が一定以上あれば2層構造
        if lv1 >= 3 and lv2 >= 3:
            return '2層構造(抑制+禁止)'
        else:
            return '禁止地区制'
    
    # 抑制区域のPearson残差が顕著に正で、禁止が特徴的でない場合
    if lv1_resid > 1.0 and lv2_resid < 1.0:
        # 禁止区域を含む場合も、統合して2層構造として扱う
        if lv2 > 0:
            return '2層構造(抑制+禁止)'
        else:
            return '抑制地区制'
    
    # Pearson残差が決定的でない場合、カウント数で判定
    if lv2 > 0:
        # 両方が一定以上(3以上)あれば2層構造
        if lv1 >= 3 and lv2 >= 3:
            return '2層構造(抑制+禁止)'
        # 抑制が禁止の2倍以上ある場合も、統合して2層構造として扱う
        elif lv1 >= lv2 * 2:
            return '2層構造(抑制+禁止)'
        else:
            return '禁止地区制'
    else:
        # 禁止区域が0で抑制区域のみの場合
        if lv1 >= 3:
            return '抑制地区制'
        else:
            return '区域設定あり(少数)'

# 分類の適用
df_with_residuals['区域類型'] = df_with_residuals.apply(classify_zone_type, axis=1)

# 結果の表示
zone_summary = df_with_residuals[['Municiparity_name', 
                         '*CLAUSE_ZONE_Lv1',
                         '*CLAUSE_ZONE_Lv1_pearson_resid',
                         '*CLAUSE_ZONE_Lv2',
                         '*CLAUSE_ZONE_Lv2_pearson_resid',
                         '*CLAUSE_RESTRICTED_ZONE',
                         '禁止区域比率',
                         '区域類型']].copy()
zone_summary.columns = ['自治体', '抑制区域(Lv1)', '抑制(残差)', '禁止区域(Lv2)', '禁止(残差)', '法定規制区域', '禁止区域比率', '区域類型']
# 残差と比率を小数点第2位まで表示
zone_summary['抑制(残差)'] = zone_summary['抑制(残差)'].round(2)
zone_summary['禁止(残差)'] = zone_summary['禁止(残差)'].round(2)
zone_summary['禁止区域比率'] = zone_summary['禁止区域比率'].round(2)
print(zone_summary.to_string(index=False))

print("\n\n区域類型の分布:")
print(df_with_residuals['区域類型'].value_counts())

print("\n\n【参考】2層構造における禁止区域比率の統計:")
two_layer = df_with_residuals[df_with_residuals['区域類型'] == '2層構造(抑制+禁止)']
if len(two_layer) > 0:
    print(f"平均: {two_layer['禁止区域比率'].mean():.2f}")
    print(f"中央値: {two_layer['禁止区域比率'].median():.2f}")
    print(f"最小値: {two_layer['禁止区域比率'].min():.2f}")
    print(f"最大値: {two_layer['禁止区域比率'].max():.2f}")

     自治体  抑制区域(Lv1)  抑制(残差)  禁止区域(Lv2)  禁止(残差)  法定規制区域  禁止区域比率        区域類型
    えりも町          0   -2.27          0   -1.07       1    0.00      区域設定なし
 かすみがうら市          0   -2.11          0   -0.99       0    0.00      区域設定なし
   かつらぎ町          0   -1.88          0   -0.88       0    0.00      区域設定なし
    さくら市          7    0.47          0   -1.14       0    0.00       抑制地区制
    つくば市          6   -0.16          6    3.87       3    0.50 2層構造(抑制+禁止)
   ときがわ町          4   -0.53          0   -1.07       0    0.00       抑制地区制
    みどり市         11    0.98          0   -1.34       1    0.00       抑制地区制
   みなかみ町          5    0.19          0   -1.01       0    0.00       抑制地区制
    みやこ町          0   -1.78          0   -0.84       0    0.00      区域設定なし
    ニセコ町          3   -0.54          0   -0.95       0    0.00       抑制地区制
     阿智村          4   -0.11          1    0.07       1    0.20 2層構造(抑制+禁止)
     愛南町          0   -1.79          0   -0.84       0    0.00      区域設定なし
  愛媛県上島町          0   -1.61          0   -0.76       0    0.00      区域設定なし
      綾町          7    1.19          3    2.03       1    0.30 2層構造(抑制+禁止)
     安中市          5    1.36          0   -0.78       0    0.00       抑制地区制
    安曇野市          6    0.12          3    1.55       2    0.33 2層構造(抑制+禁止)
     安平町          0   -1.87          6    5.95       1    1.00       禁止地区制
     伊達市          7    1.08          0   -1.01       0    0.00       抑制地区制
     伊東市          6    0.86          0   -0.96       0    0.00       抑制地区制
   伊豆の国市          4    1.35          0   -0.67       0    0.00       抑制地区制
     伊豆市          4   -0.28          0   -1.01       1    0.00       抑制地区制
     伊那市          6    2.03          2    1.84       2    0.25       禁止地区制
     伊方町          3   -0.12          2    1.54       1    0.40       禁止地区制
    伊万里市          5    1.92          0   -0.69       0    0.00       抑制地区制
  茨城県守谷市          1   -0.88          0   -0.72       0    0.00  区域設定あり(少数)
茨城県常陸太田市          6    1.47          1    0.31       0    0.14 2層構造(抑制+禁止)
     茨城町          3    0.40          0   -0.72       0    0.00       抑制地区制
     宇佐市          3    0.09          0   -0.79       0    0.00       抑制地区制
     宇治市          1   -0.90          4    4.80       1    0.80       禁止地区制
     宇陀市          0   -1.99          0   -0.93       0    0.00      区域設定なし
    宇都宮市          8    0.09          0   -1.30       4    0.00       抑制地区制
    宇和島市          2   -2.43          7    3.39       1    0.78       禁止地区制
     羽幌町          0   -3.37          0   -1.58       0    0.00      区域設定なし
     益子町          8    0.36          0   -1.25       3    0.00       抑制地区制
     越生町          0   -2.58          5    2.92       1    1.00       禁止地区制
     遠野市          2   -0.94          0   -0.92       1    0.00  区域設定あり(少数)
     塩尻市          3   -1.10          2    0.69       1    0.40       禁止地区制
     塩谷町         16    1.98          0   -1.47       3    0.00       抑制地区制
     岡垣町          3   -0.16          3    2.67       0    0.50 2層構造(抑制+禁止)
  岡山県美作市          0   -1.33          0   -0.62       0    0.00      区域設定なし
     下関市          0   -2.40          0   -1.12       0    0.00      区域設定なし
     下妻市         10    1.08          0   -1.25       3    0.00       抑制地区制
     下田市          7    1.35          0   -0.96       1    0.00       抑制地区制
     加美町         11    2.35          0   -1.10       2    0.00       抑制地区制
     可児市         15    3.65          0   -1.15       0    0.00       抑制地区制
    我孫子市          0   -1.19          0   -0.56       0    0.00      区域設定なし
     皆野町          1   -2.20          0   -1.21       0    0.00  区域設定あり(少数)
     角田市          4   -0.06          0   -0.95       1    0.00       抑制地区制
     掛川市          6    0.82          0   -0.97       1    0.00       抑制地区制
     笠間市          5    1.13          0   -0.82       0    0.00       抑制地区制
     滑川町          6    0.25          0   -1.09       0    0.00       抑制地区制
      関市          0   -1.74          0   -0.82       0    0.00      区域設定なし
     丸森町          9    1.73          8    6.49       1    0.47 2層構造(抑制+禁止)
     岩国市          6    0.74          0   -0.99       3    0.00       抑制地区制
     嬉野市          5   -0.75          0   -1.24       0    0.00       抑制地区制
     寄居町          3   -0.10          0   -0.84       0    0.00       抑制地区制
    紀美野町          0   -2.23          0   -1.05       0    0.00      区域設定なし
     鬼北町          0   -1.98          1    0.15       0    1.00       禁止地区制
     亀岡市          0   -1.64          2    1.84       0    1.00       禁止地区制
     菊川市          6    1.33          0   -0.88       1    0.00       抑制地区制
     菊池市          3   -1.90          0   -1.37       2    0.00       抑制地区制
     吉岡町         11    3.88          0   -0.89       0    0.00       抑制地区制
     吉賀町          0   -2.04          5    4.27       0    1.00       禁止地区制
     吉見町          3   -0.88          0   -1.04       0    0.00       抑制地区制
     宮古市          0   -3.11          0   -1.46       0    0.00      区域設定なし
     牛久市          5    0.53          0   -0.93       0    0.00       抑制地区制
    京丹後市          0   -1.42          0   -0.67       0    0.00      区域設定なし
    京丹波町          5   -0.81          4    1.93       0    0.44 2層構造(抑制+禁止)
    京田辺市          1   -2.26          4    2.00       1    0.80       禁止地区制
     喬木村          4    0.41          1    0.34       0    0.20 2層構造(抑制+禁止)
      境町          0   -1.67          0   -0.78       0    0.00      区域設定なし
     橋本市          0   -1.30          0   -0.61       0    0.00      区域設定なし
     鏡野町          0   -1.41          0   -0.66       0    0.00      区域設定なし
     玉川村          5    0.66          0   -0.91       0    0.00       抑制地区制
     桐生市         20    3.57          0   -1.42       0    0.00       抑制地区制
 桐生市_改正前         15    2.99          0   -1.25       0    0.00       抑制地区制
      錦町          0   -2.07          0   -0.97       0    0.00      区域設定なし
     金沢市          5    0.73          6    5.83       2    0.55 2層構造(抑制+禁止)
     串本町          0   -2.16          0   -1.01       0    0.00      区域設定なし
     釧路市          7    0.22          6    3.85       1    0.46 2層構造(抑制+禁止)
     熊取町          3    0.65          0   -0.67       1    0.00       抑制地区制
     熊谷市          5    0.00          0   -1.05       0    0.00       抑制地区制
     栗原市          4    1.11          0   -0.71       0    0.00       抑制地区制
     恵那市          1   -2.42          0   -1.30       0    0.00  区域設定あり(少数)
     結城市          3   -0.57          0   -0.96       1    0.00       抑制地区制
     月形町          5    0.87          0   -0.86       1    0.00       抑制地区制
      原村          3    0.62          0   -0.68       1    0.00       抑制地区制
     古河市          0   -1.53          0   -0.72       0    0.00      区域設定なし
    古座川町          0   -1.92          0   -0.90       0    0.00      区域設定なし
     古平町          0   -1.93          0   -0.91       0    0.00      区域設定なし
     湖西市          5    1.36          0   -0.78       0    0.00       抑制地区制
     五霞町          3    0.54          0   -0.70       0    0.00       抑制地区制
     五條市          6    1.28          1    0.24       1    0.14 2層構造(抑制+禁止)
     御宿町          7    1.32          0   -0.97       0    0.00       抑制地区制
     御所市         12    3.06          3    1.77       2    0.20 2層構造(抑制+禁止)
     御嵩町          0   -1.47          0   -0.69       1    0.00      区域設定なし
    御前崎市          6    1.73          0   -0.81       0    0.00       抑制地区制
     厚真町          0   -1.34          4    5.71       1    1.00       禁止地区制
     江差町          0   -2.01          0   -0.94       0    0.00      区域設定なし
     高崎市         12    2.61          0   -1.12       0    0.00       抑制地区制
     高山村          9   -0.16          0   -1.45       3    0.00       抑制地区制
     高取町          5    1.88          2    2.17       1    0.29       禁止地区制
  高知県須崎市          0   -1.45          0   -0.68       0    0.00      区域設定なし
     高槻市          7    1.67          0   -0.91       1    0.00       抑制地区制
     国見町          0   -2.00          0   -0.94       0    0.00      区域設定なし
     今金町          7    2.38          0   -0.80       0    0.00       抑制地区制
    佐久穂町          1   -1.81          2    0.83       1    0.67       禁止地区制
     佐伯市          2   -0.88          0   -0.90       0    0.00  区域設定あり(少数)
     佐野市          7   -0.03          0   -1.25       1    0.00       抑制地区制
     坂東市          4    0.84          0   -0.76       0    0.00       抑制地区制
     桜井市          5    0.64          3    2.39       1    0.38 2層構造(抑制+禁止)
     三郷町          6    2.18          2    1.93       1    0.25       禁止地区制
     三木市          0   -1.45          1    0.79       0    1.00       禁止地区制
     山形村          8    1.81          0   -0.97       1    0.00       抑制地区制
     山元町          7    2.11          0   -0.84       0    0.00       抑制地区制
     士別市          0   -2.37          3    1.58       0    1.00       禁止地区制
     市川町          2   -0.61          1    0.39       0    0.33 2層構造(抑制+禁止)
     志摩市          9    3.19          0   -0.85       0    0.00       抑制地区制
     鹿沼市         12    1.96          0   -1.23       0    0.00       抑制地区制
     鹿島市          7    1.17          0   -1.00       0    0.00       抑制地区制
     鹿嶋市          6    1.23          0   -0.90       0    0.00       抑制地区制
     宍粟市          0   -2.30          3    1.71       0    1.00       禁止地区制
     雫石町          5   -0.01          1   -0.10       1    0.17 2層構造(抑制+禁止)
    七ヶ宿町          3    0.45          0   -0.71       0    0.00       抑制地区制
     柴田町          8    2.04          0   -0.93       0    0.00       抑制地区制
     斜里町          0   -1.83          3    2.63       0    1.00       禁止地区制
     渋川市         12    3.71          0   -0.97       1    0.00       抑制地区制
     宿毛市          0   -0.89          0   -0.42       0    0.00      区域設定なし
     女川町          8    2.13          0   -0.92       0    0.00       抑制地区制
     小海町          4   -0.20          4    3.07       4    0.50 2層構造(抑制+禁止)
     小諸市          2   -0.54          2    1.69       2    0.50       禁止地区制
     小川町          3   -0.55          0   -0.95       1    0.00       抑制地区制
     松江市          1   -2.05          4    2.32       1    0.80       禁止地区制
     松崎町          7    1.59          0   -0.92       0    0.00       抑制地区制
     松田町          0   -2.23          0   -1.04       0    0.00      区域設定なし
     松本市         10    1.86          6    4.29       2    0.38 2層構造(抑制+禁止)
     沼津市          5   -0.18          0   -1.09       0    0.00       抑制地区制
     焼津市          6    2.00          0   -0.77       0    0.00       抑制地区制
     上田市          7    0.92          0   -1.04       2    0.00       抑制地区制
   常陸大宮市         10    1.09          8    5.16       0    0.44 2層構造(抑制+禁止)
     色麻町          7    1.42          0   -0.95       0    0.00       抑制地区制
     信濃町          7    2.68          0   -0.76       1    0.00       抑制地区制
     新宮市          0   -1.95          0   -0.91       0    0.00      区域設定なし
     新城市          0   -1.61          0   -0.76       0    0.00      区域設定なし
     新得町          0   -1.94          6    5.69       0    1.00       禁止地区制
     新富町          5    2.09          0   -0.67       0    0.00       抑制地区制
     真岡市          3   -1.06          0   -1.10       0    0.00       抑制地区制
     真庭市          5    1.88          0   -0.70       0    0.00       抑制地区制
     神戸市          0   -2.35          5    3.43       0    1.00       禁止地区制
     諏訪市          3    1.39          0   -0.55       1    0.00       抑制地区制
     須崎市          0   -2.27          0   -1.07       0    0.00      区域設定なし
     瑞浪市          9    2.26          0   -0.97       0    0.00       抑制地区制
     裾野市          5    0.99          0   -0.84       0    0.00       抑制地区制
     瀬戸市         12    4.62          0   -0.87       0    0.00       抑制地区制
     生坂村          7    1.12          0   -1.01       2    0.00       抑制地区制
     西郷村          0   -1.25          0   -0.58       0    0.00      区域設定なし
     西桂町          0   -1.99          0   -0.94       0    0.00      区域設定なし
 西桂町_改正前          1   -1.35          0   -0.88       0    0.00  区域設定あり(少数)
     西予市          7    1.02          5    3.85       4    0.42 2層構造(抑制+禁止)
     西脇市          0   -1.91          0   -0.90       0    0.00      区域設定なし
     青木村          0   -1.94          2    1.29       0    1.00       禁止地区制
 静岡県西伊豆町          5    1.80          0   -0.71       0    0.00       抑制地区制
 静岡県東伊豆町          5    1.30          0   -0.79       0    0.00       抑制地区制
     石岡市          0   -1.51          0   -0.71       1    0.00      区域設定なし
     石巻市          8    1.91          0   -0.95       0    0.00       抑制地区制
     赤磐市          3    0.04          0   -0.80       0    0.00       抑制地区制
     赤穂市          6    0.93          0   -0.95       0    0.00       抑制地区制
     仙台市          4   -1.91          0   -1.49       0    0.00       抑制地区制
  千葉県長柄町          1   -0.08          0   -0.49       0    0.00  区域設定あり(少数)
     川崎町         15    2.85         13    8.99       2    0.46 2層構造(抑制+禁止)
     川島町          6   -0.23          0   -1.20       0    0.00       抑制地区制
     川俣町          0   -1.45          0   -0.68       0    0.00      区域設定なし
     前橋市         10    2.63          0   -0.99       0    0.00       抑制地区制
     蔵王町         11    2.19         11    8.66       0    0.50 2層構造(抑制+禁止)
     足利市         11    0.82          0   -1.38       1    0.00       抑制地区制
     村田町          5    0.80          0   -0.88       0    0.00       抑制地区制
     多可町          0   -2.67          0   -1.25       0    0.00      区域設定なし
     太田市         17    3.77          0   -1.24       1    0.00       抑制地区制
     袋井市          3   -2.47          0   -1.58       0    0.00       抑制地区制
    大宜味村          1   -0.81          0   -0.70       0    0.00  区域設定あり(少数)
     大玉村          0   -1.44          0   -0.67       0    0.00      区域設定なし
     大空町          5    0.55          0   -0.93       1    0.00       抑制地区制
     大桑村          7    0.66          0   -1.10       0    0.00       抑制地区制
     大崎市         14    1.86          0   -1.37       0    0.00       抑制地区制
     大子町          3    0.13          2    1.77       0    0.40       禁止地区制
     大洲市          4    0.28          4    3.70       2    0.50 2層構造(抑制+禁止)
     大町市          6   -0.12          3    1.37       2    0.33 2層構造(抑制+禁止)
     大町町          4    0.78          0   -0.77       0    0.00       抑制地区制
     大津市         12    3.78          1    0.07       1    0.08 2層構造(抑制+禁止)
     大津町          8    1.35          0   -1.05       1    0.00       抑制地区制
    大田原市          7    0.05          0   -1.23       0    0.00       抑制地区制
     大府市          0   -1.96          0   -0.92       0    0.00      区域設定なし
   大網白里市          1   -1.41          0   -0.91       0    0.00  区域設定あり(少数)
     辰野町          1   -1.21          2    1.57       1    0.67       禁止地区制
     丹波市          5    0.80          2    1.40       2    0.29       禁止地区制
     竹田市          0   -0.89          0   -0.42       0    0.00      区域設定なし
     秩父市          1   -1.48          0   -0.93       0    0.00  区域設定あり(少数)
     中川村          0   -2.14          8    6.95       0    1.00       禁止地区制
    中津川市          4   -0.15          0   -0.97       1    0.00       抑制地区制
     朝日村          3    0.75          0   -0.66       0    0.00       抑制地区制
     長沼町          7    0.98          0   -1.03       2    0.00       抑制地区制
  長野県松川村          0   -2.43          0   -1.14       0    0.00      区域設定なし
  長野県筑北村          4    0.03          0   -0.93       1    0.00       抑制地区制
     長野市          0   -2.99          0   -1.40       0    0.00      区域設定なし
     鳥羽市         10    4.81          0   -0.74       1    0.00       抑制地区制
     鶴居村          5    0.51          0   -0.94       0    0.00       抑制地区制
     天草市          2    0.36          0   -0.58       0    0.00  区域設定あり(少数)
     天理市          7   -1.49          2   -0.42       1    0.22 2層構造(抑制+禁止)
     田川市          6    2.84          0   -0.66       0    0.00       抑制地区制
     田村市          6    0.99          1    0.12       1    0.14 2層構造(抑制+禁止)
     登米市          6    2.03          0   -0.77       0    0.00       抑制地区制
     登別市          8    1.35          5    3.72       2    0.38 2層構造(抑制+禁止)
     砥部町          0   -2.37          1   -0.21       0    1.00       禁止地区制
     土佐市          0   -2.36          0   -1.11       0    0.00      区域設定なし
   土佐清水市          0   -1.68          0   -0.79       0    0.00      区域設定なし
     島田市          0   -1.47          0   -0.69       0    0.00      区域設定なし
     東栄町         11    4.08          0   -0.87       0    0.00       抑制地区制
     東海村          9    2.32          0   -0.96       0    0.00       抑制地区制
    東広島市          4    1.08          0   -0.72       0    0.00       抑制地区制
    東松山市          4   -0.34          5    3.88       0    0.56 2層構造(抑制+禁止)
      東村          1   -1.57          0   -0.96       0    0.00  区域設定あり(少数)
    湯河原町         19    5.13          0   -1.17       3    0.00       抑制地区制
     藤枝市          4    1.31          0   -0.68       0    0.00       抑制地区制
    苫小牧市          1   -1.52          4    3.29       0    0.80       禁止地区制
     奈義町          0   -1.52          0   -0.71       0    0.00      区域設定なし
     那珂市          4   -0.06          0   -0.95       0    0.00       抑制地区制
   那須塩原市          8    1.35          4    2.77       3    0.33 2層構造(抑制+禁止)
     那須町          5    0.37          0   -0.96       0    0.00       抑制地区制
   那智勝浦町          0   -2.02          0   -0.95       0    0.00      区域設定なし
     内子町          4    1.24          0   -0.69       0    0.00       抑制地区制
     楢葉町          0   -3.12          0   -1.47       0    0.00      区域設定なし
    南伊勢町         18    4.67          0   -1.18       2    0.00       抑制地区制
     南関町          1   -1.52          0   -0.94       0    0.00  区域設定あり(少数)
    南三陸町          4    2.57          0   -0.51       0    0.00       抑制地区制
    南山城村          0   -2.43          5    3.24       0    1.00       禁止地区制
    南相馬市          7    1.54          0   -0.93       0    0.00       抑制地区制
     南丹市          0   -1.54          0   -0.72       0    0.00      区域設定なし
    南知多町         10    1.90          0   -1.10       0    0.00       抑制地区制
     南砺市          0   -2.41          3    1.52       1    1.00       禁止地区制
    南島原市         29    5.09          0   -1.60       2    0.00       抑制地区制
    南箕輪村         10    2.81          2    1.11       1    0.17       禁止地区制
    南木曽町          7    1.84          0   -0.88       0    0.00       抑制地区制
     日光市          8    1.57          0   -1.01       1    0.00       抑制地区制
     日高市          0   -1.86          0   -0.87       0    0.00      区域設定なし
     日高町          0   -2.07          4    3.16       1    1.00       禁止地区制
     日出町          4   -0.49          0   -1.06       1    0.00       抑制地区制
     日置市          0   -1.98          0   -0.93       0    0.00      区域設定なし
     日立市          5    0.28          0   -0.99       0    0.00       抑制地区制
     入間市          4    1.01          0   -0.73       0    0.00       抑制地区制
     熱海市          5    0.24          0   -0.99       0    0.00       抑制地区制
     能勢町          0   -2.41          2    0.64       0    1.00       禁止地区制
     売木村          0   -1.47          0   -0.69       0    0.00      区域設定なし
     白石市         10    1.97          0   -1.09       0    0.00       抑制地区制
     白馬村          1   -0.95          1    0.61       1    0.50       禁止地区制
     白老町          0   -2.11          5    4.07       2    1.00       禁止地区制
     函南町          5    1.88          0   -0.70       0    0.00       抑制地区制
    八千代町          7    1.00          0   -1.03       0    0.00       抑制地区制
     八幡市          5    0.23          6    5.02       0    0.55 2層構造(抑制+禁止)
    八幡浜市          6    0.43          0   -1.05       2    0.00       抑制地区制
    八幡平市          4   -0.47          3    1.79       1    0.43 2層構造(抑制+禁止)
     鳩山町          1   -1.71          0   -1.02       0    0.00  区域設定あり(少数)
     飯塚市          4   -0.23          4    3.03       1    0.50 2層構造(抑制+禁止)
     飯能市          4    0.58          4    4.11       0    0.50 2層構造(抑制+禁止)
     飯豊町          0   -1.29          0   -0.60       0    0.00      区域設定なし
     磐田市          0   -1.70          0   -0.80       0    0.00      区域設定なし

In [11]:
# 禁止区域(Lv2)の実数値をリストとして出力
lv2_list = df_with_residuals['*CLAUSE_ZONE_Lv2'].tolist()
print("禁止区域(Lv2)の実数値リスト:")
print(lv2_list)

禁止区域(Lv2)の実数値リスト:
[0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 1, 0, 0, 3, 0, 3, 6, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 4, 0, 0, 7, 0, 0, 5, 0, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 1, 2, 0, 0, 0, 5, 0, 0, 0, 0, 4, 4, 1, 0, 0, 0, 0, 0, 0, 0, 6, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 3, 2, 1, 0, 0, 3, 1, 0, 0, 0, 0, 3, 1, 0, 0, 3, 0, 0, 0, 4, 2, 0, 4, 0, 0, 6, 0, 0, 0, 8, 0, 0, 0, 0, 6, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 3, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 5, 1, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 4, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 3, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0, 2, 0, 0, 1, 5, 0, 0, 6, 0, 3, 0, 4, 4, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 5, 2, 1, 1, 0, 1, 0, 1, 3, 0, 0, 1, 9, 0, 0, 0, 1, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0]

## 5. 住民参加・手続き重視度の評価

住民関与や手続きに関する条項から、プロセス重視型かどうかを評価します。

**住民参加スコア = 説明会 + 意見聴取 + 住民関与**  
**手続きスコア = 協議 + 行政通知 + 届出**

In [12]:
# 住民参加スコアの計算
df_with_residuals['住民参加スコア'] = (df_with_residuals['*CLAUSE_EXPLANATION'] + 
                            df_with_residuals['*CLAUSE_HEARING'] + 
                            df_with_residuals['*STAKEHOLDER_RESIDENTS'])

# 手続きスコアの計算
df_with_residuals['手続きスコア'] = (df_with_residuals['*PROCEDURE_CONSULTAION'] + 
                          df_with_residuals['*PROCEDURE_NOTICE_MUNICIPARITY'] + 
                          df_with_residuals['*PROCEDURE_NOTICE_OPERATOR'])

# 正規化
df_with_residuals['住民参加スコア(正規化)'] = df_with_residuals['住民参加スコア'] / df_with_residuals['ケース数'] * 100
df_with_residuals['手続きスコア(正規化)'] = df_with_residuals['手続きスコア'] / df_with_residuals['ケース数'] * 100

# プロセス重視度の分類
def classify_process_orientation(row):
    resident = row['住民参加スコア(正規化)']
    procedure = row['手続きスコア(正規化)']
    
    if resident >= 10 and procedure >= 15:
        return '住民参加・手続き重視型'
    elif resident >= 10:
        return '住民参加重視型'
    elif procedure >= 15:
        return '手続き重視型'
    else:
        return '標準型'

df_with_residuals['プロセス重視度'] = df_with_residuals.apply(classify_process_orientation, axis=1)

# 結果の表示
process_summary = df_with_residuals[['Municiparity_name',
                           '住民参加スコア',
                           '住民参加スコア(正規化)',
                           '手続きスコア',
                           '手続きスコア(正規化)',
                           'プロセス重視度']].copy()
process_summary.columns = ['自治体', '住民参加', '住民参加(正規化)', '手続き', '手続き(正規化)', 'プロセス重視度']
process_summary['住民参加(正規化)'] = process_summary['住民参加(正規化)'].round(2)
process_summary['手続き(正規化)'] = process_summary['手続き(正規化)'].round(2)
process_summary_sorted = process_summary.sort_values('住民参加(正規化)', ascending=False)
print(process_summary_sorted.to_string(index=False))

print("\n\nプロセス重視度の分布:")
print(df_with_residuals['プロセス重視度'].value_counts())

     自治体  住民参加  住民参加(正規化)  手続き  手続き(正規化)     プロセス重視度
     売木村    23      38.33   31     51.67 住民参加・手続き重視型
     山形村    44      37.29   59     50.00 住民参加・手続き重視型
     小海町    45      36.89   49     40.16 住民参加・手続き重視型
     志摩市    33      36.67   48     53.33 住民参加・手続き重視型
  福岡県直方市    17      34.69   27     55.10 住民参加・手続き重視型
    南伊勢町    59      33.91   74     42.53 住民参加・手続き重視型
    龍ケ崎市    22      31.43   32     45.71 住民参加・手続き重視型
     石岡市    19      30.16   37     58.73 住民参加・手続き重視型
     信濃町    22      30.14   31     42.47 住民参加・手続き重視型
    南知多町    46      30.07   67     43.79 住民参加・手続き重視型
     小諸市    24      29.63   32     39.51 住民参加・手続き重視型
     美祢市    13      29.55   16     36.36 住民参加・手続き重視型
     瑞浪市    35      29.41   50     42.02 住民参加・手続き重視型
     牛久市    31      28.44   57     52.29 住民参加・手続き重視型
     平群町    21      28.38   36     48.65 住民参加・手続き重視型
     五霞町    17      27.87   44     72.13 住民参加・手続き重視型
     小川町    31      27.19   67     58.77 住民参加・手続き重視型
     伊那市    20      27.03   26     35.14 住民参加・手続き重視型
     湖西市    20      26.32   37     48.68 住民参加・手続き重視型
    大宜味村    16      26.23   34     55.74 住民参加・手続き重視型
     松本市    39      25.16   75     48.39 住民参加・手続き重視型
     大洲市    24      25.00   61     63.54 住民参加・手続き重視型
     加美町    37      24.34   52     34.21 住民参加・手続き重視型
     三郷町    17      24.29   32     45.71 住民参加・手続き重視型
    南三陸町     8      24.24   18     54.55 住民参加・手続き重視型
     南丹市    16      24.24   47     71.21 住民参加・手続き重視型
     上田市    33      24.09   78     56.93 住民参加・手続き重視型
     長沼町    32      23.88   59     44.03 住民参加・手続き重視型
     寄居町    21      23.86   56     63.64 住民参加・手続き重視型
     諏訪市     9      23.68   19     50.00 住民参加・手続き重視型
 静岡県東伊豆町    18      23.08   29     37.18 住民参加・手続き重視型
    南箕輪村    27      23.08   51     43.59 住民参加・手続き重視型
     亀岡市    17      22.97   41     55.41 住民参加・手続き重視型
  長野県筑北村    25      22.94   52     47.71 住民参加・手続き重視型
     熊取町    13      22.81   31     54.39 住民参加・手続き重視型
     宇治市    15      22.73   35     53.03 住民参加・手続き重視型
      原村    13      22.41   33     56.90 住民参加・手続き重視型
      岬町    13      22.41   33     56.90 住民参加・手続き重視型
     鹿島市    28      22.40   76     60.80 住民参加・手続き重視型
     安中市    17      22.37   30     39.47 住民参加・手続き重視型
     今金町    18      22.22   32     39.51 住民参加・手続き重視型
      境町    17      22.08   43     55.84 住民参加・手続き重視型
      錦町    26      22.03   51     43.22 住民参加・手続き重視型
     木祖村    15      21.74   19     27.54 住民参加・手続き重視型
     美浜町    21      21.65   31     31.96 住民参加・手続き重視型
     登米市    16      21.62   36     48.65 住民参加・手続き重視型
     真庭市    13      21.31   20     32.79 住民参加・手続き重視型
     高取町    13      21.31   29     47.54 住民参加・手続き重視型
    つくば市    37      20.90   68     38.42 住民参加・手続き重視型
     富谷市    11      20.75   35     66.04 住民参加・手続き重視型
  岡山県美作市    10      20.41   25     51.02 住民参加・手続き重視型
     須崎市    29      20.28   36     25.17 住民参加・手続き重視型
    安曇野市    32      20.25   45     28.48 住民参加・手続き重視型
    南山城村    33      20.12   71     43.29 住民参加・手続き重視型
     吉賀町    23      20.00   36     31.30 住民参加・手続き重視型
     川島町    36      19.78   80     43.96 住民参加・手続き重視型
     松江市    33      19.76   60     35.93 住民参加・手続き重視型
     那須町    23      19.66   64     54.70 住民参加・手続き重視型
     名張市    10      19.61   25     49.02 住民参加・手続き重視型
     熊谷市    27      19.57   66     47.83 住民参加・手続き重視型
     大津町    27      19.57   60     43.48 住民参加・手続き重視型
     豊丘村    17      19.54   48     55.17 住民参加・手続き重視型
     菊池市    46      19.41   78     32.91 住民参加・手続き重視型
     高山村    51      19.39   93     35.36 住民参加・手続き重視型
     角田市    22      19.30   50     43.86 住民参加・手続き重視型
     色麻町    22      19.30   41     35.96 住民参加・手続き重視型
     飯能市    16      19.28   39     46.99 住民参加・手続き重視型
     坂東市    14      19.18   42     57.53 住民参加・手続き重視型
     湧別町    32      19.16   67     40.12 住民参加・手続き重視型
     橋本市     9      19.15   22     46.81 住民参加・手続き重視型
    宇和島市    50      19.01   87     33.08 住民参加・手続き重視型
     吉岡町    19      19.00   48     48.00 住民参加・手続き重視型
     西予市    25      18.94   51     38.64 住民参加・手続き重視型
     蔵王町    30      18.87  102     64.15 住民参加・手続き重視型
     麻績村    18      18.75   26     27.08 住民参加・手続き重視型
    七ヶ宿町    12      18.75   46     71.88 住民参加・手続き重視型
     砥部町    29      18.71   64     41.29 住民参加・手続き重視型
     前橋市    23      18.70   49     39.84 住民参加・手続き重視型
     標津町    17      18.68   37     40.66 住民参加・手続き重視型
     御所市    26      18.44   39     27.66 住民参加・手続き重視型
     秩父市    20      18.35   55     50.46 住民参加・手続き重視型
    富士見町    15      18.29   37     45.12 住民参加・手続き重視型
     青木村    19      18.27   66     63.46 住民参加・手続き重視型
     南砺市    29      18.01   41     25.47 住民参加・手続き重視型
     厚真町     9      18.00   17     34.00 住民参加・手続き重視型
     伊方町    16      17.98   36     40.45 住民参加・手続き重視型
     女川町    19      17.92   52     49.06 住民参加・手続き重視型
     入間市    12      17.91   39     58.21 住民参加・手続き重視型
     平谷村    10      17.86   26     46.43 住民参加・手続き重視型
    佐久穂町    25      17.73   57     40.43 住民参加・手続き重視型
     鳥羽市    12      17.65   24     35.29 住民参加・手続き重視型
     渋川市    21      17.65   47     39.50 住民参加・手続き重視型
     石巻市    20      17.54   57     50.00 住民参加・手続き重視型
     安平町    17      17.53   31     31.96 住民参加・手続き重視型
   大網白里市    18      17.48   36     34.95 住民参加・手続き重視型
    南相馬市    19      17.43   36     33.03 住民参加・手続き重視型
     大町町    13      17.33   30     40.00 住民参加・手続き重視型
     桐生市    44      17.32   96     37.80 住民参加・手続き重視型
     野田市    21      17.21   79     64.75 住民参加・手続き重視型
     日光市    22      17.19   69     53.91 住民参加・手続き重視型
     五條市    17      17.17   29     29.29 住民参加・手続き重視型
      東村    20      17.09   45     38.46 住民参加・手続き重視型
     阿智村    20      17.09   58     49.57 住民参加・手続き重視型
     月形町    16      17.02   44     46.81 住民参加・手続き重視型
     丸森町    24      17.02   78     55.32 住民参加・手続き重視型
    和歌山市    34      17.00   67     33.50 住民参加・手続き重視型
     南関町    19      16.96   44     39.29 住民参加・手続き重視型
    東広島市    11      16.92   42     64.62 住民参加・手続き重視型
     越生町    31      16.85   85     46.20 住民参加・手続き重視型
    伊万里市    10      16.67   25     41.67 住民参加・手続き重視型
     塩谷町    45      16.61   99     36.53 住民参加・手続き重視型
     由布市    10      16.39   36     59.02 住民参加・手続き重視型
     桜井市    17      16.35   30     28.85 住民参加・手続き重視型
     串本町    21      16.28   38     29.46 住民参加・手続き重視型
     伊達市    21      16.28   53     41.09 住民参加・手続き重視型
     下妻市    32      16.24   75     38.07 住民参加・手続き重視型
     長野市    40      16.19   95     38.46 住民参加・手続き重視型
     鳩山町    21      16.15   69     53.08 住民参加・手続き重視型
    苫小牧市    18      16.07   50     44.64 住民参加・手続き重視型
   ときがわ町    23      15.97   72     50.00 住民参加・手続き重視型
     恵那市    34      15.89   71     33.18 住民参加・手続き重視型
     川崎町    32      15.84   81     40.10 住民参加・手続き重視型
     鹿嶋市    16      15.84   33     32.67 住民参加・手続き重視型
     豊橋市    15      15.79   40     42.11 住民参加・手続き重視型
     東栄町    15      15.79   33     34.74 住民参加・手続き重視型
     中川村    20      15.75   58     45.67 住民参加・手続き重視型
     大空町    17      15.74   43     39.81 住民参加・手続き重視型
     高崎市    25      15.72   49     30.82 住民参加・手続き重視型
     栗原市    10      15.62   33     51.56 住民参加・手続き重視型
     柴田町    17      15.60   52     47.71 住民参加・手続き重視型
     玉川村    16      15.53   40     38.83 住民参加・手続き重視型
     藤枝市     9      15.52   24     41.38 住民参加・手続き重視型
     大町市    27      15.52   66     37.93 住民参加・手続き重視型
     塩尻市    24      15.48   73     47.10 住民参加・手続き重視型
     嵐山町    52      15.43  131     38.87 住民参加・手続き重視型
    えりも町    22      15.38   43     30.07 住民参加・手続き重視型
    我孫子市     6      15.38   16     41.03 住民参加・手続き重視型
     飯塚市    19      15.32   46     37.10 住民参加・手続き重視型
     田村市    17      15.32   30     27.03 住民参加・手続き重視型
  愛媛県上島町    11      15.28   30     41.67 住民参加・手続き重視型
    東松山市    20      15.27   83     63.36 住民参加・手続き重視型
     豊能町    21      15.22   48     34.78 住民参加・手続き重視型
    紀美野町    21      15.22   37     26.81 住民参加・手続き重視型
     鉾田市    57      15.20  139     37.07 住民参加・手続き重視型
     釧路市    27      15.17   74     41.57 住民参加・手続き重視型
     茨城町    10      15.15   35     53.03 住民参加・手続き重視型
     木曽町    25      15.06   45     27.11 住民参加・手続き重視型
     斜里町    14      15.05   35     37.63 住民参加・手続き重視型
     内子町     9      15.00   31     51.67 住民参加・手続き重視型
     土佐市    23      14.94   48     31.17 住民参加・手続き重視型
     瀬戸市    14      14.74   61     64.21 住民参加・手続き重視型
     白老町    18      14.63   70     56.91 住民参加・手続き重視型
    京田辺市    28      14.58   67     34.90 住民参加・手続き重視型
     利根町    18      14.52   56     45.16 住民参加・手続き重視型
     登別市    20      14.49   49     35.51 住民参加・手続き重視型
     白馬村    10      14.49   28     40.58 住民参加・手続き重視型
     村田町    14      14.43   56     57.73 住民参加・手続き重視型
     雫石町    20      14.39   60     43.17 住民参加・手続き重視型
     矢祭町    21      14.38   56     38.36 住民参加・手続き重視型
    南木曽町    14      14.29   54     55.10 住民参加・手続き重視型
    大田原市    27      14.21   81     42.63 住民参加・手続き重視型
     茂木町    27      14.21   81     42.63 住民参加・手続き重視型
   みなかみ町    18      14.17   60     47.24 住民参加・手続き重視型
   那智勝浦町    16      14.16   37     32.74 住民参加・手続き重視型
    毛呂山町    16      14.16   61     53.98 住民参加・手続き重視型
     大府市    15      14.15   59     55.66 住民参加・手続き重視型
     遠野市    15      14.15   48     45.28 住民参加・手続き重視型
     大玉村     8      14.04   24     42.11 住民参加・手続き重視型
     滑川町    21      14.00   67     44.67 住民参加・手続き重視型
    木古内町    14      14.00   33     33.00 住民参加・手続き重視型
     天草市     6      13.95   21     48.84 住民参加・手続き重視型
     鬼北町    15      13.89   33     30.56 住民参加・手続き重視型
     新城市    10      13.89   42     58.33 住民参加・手続き重視型
  高知県須崎市     8      13.79   16     27.59 住民参加・手続き重視型
     芳賀町    24      13.64   80     45.45 住民参加・手続き重視型
     八幡市    17      13.60   43     34.40 住民参加・手続き重視型
     皆野町    25      13.51   71     38.38 住民参加・手続き重視型
    北相木村    12      13.33   29     32.22 住民参加・手続き重視型
     喬木村    12      13.33   30     33.33 住民参加・手続き重視型
     白石市    20      13.33   62     41.33 住民参加・手続き重視型
     佐野市    26      13.27   69     35.20 住民参加・手続き重視型
     防府市    14      13.21   30     28.30 住民参加・手続き重視型
     鹿沼市    25      13.16   50     26.32 住民参加・手続き重視型
     赤穂市    15      13.16   38     33.33 住民参加・手続き重視型
     大崎市    31      13.08   66     27.85 住民参加・手続き重視型
     朝日村     7      12.96   32     59.26 住民参加・手続き重視型
     大津市    15      12.82   42     35.90 住民参加・手続き重視型
    古座川町    13      12.75   34     33.33 住民参加・手続き重視型
     西桂町    14      12.73   46     41.82 住民参加・手続き重視型
 静岡県西伊豆町     8      12.70   25     39.68 住民参加・手続き重視型
     富岡市    24      12.63   56     29.47 住民参加・手続き重視型
     新宮市    13      12.38   34     32.38 住民参加・手続き重視型
     太田市    24      12.37   56     28.87 住民参加・手続き重視型
     古河市     8      12.31   45     69.23 住民参加・手続き重視型
   伊豆の国市     7      12.28   26     45.61 住民参加・手続き重視型
   常陸大宮市    24      12.24   78     39.80 住民参加・手続き重視型
     士別市    19      12.18   65     41.67 住民参加・手続き重視型
    宇都宮市    26      12.15   77     35.98 住民参加・手続き重視型
    京丹波町    24      12.12   62     31.31 住民参加・手続き重視型
     岡垣町    11      12.09   41     45.05 住民参加・手続き重視型
    御前崎市    10      12.05   23     27.71 住民参加・手続き重視型
     本庄市    15      12.00   50     40.00 住民参加・手続き重視型
     焼津市     9      12.00   17     22.67 住民参加・手続き重視型
     東海村    14      11.97   51     43.59 住民参加・手続き重視型
     下関市    19      11.95   50     31.45 住民参加・手続き重視型
     宇陀市    13      11.93   61     55.96 住民参加・手続き重視型
      関市    10      11.90   45     53.57 住民参加・手続き重視型
     佐伯市    12      11.76   39     38.24 住民参加・手続き重視型
    さくら市    19      11.73   38     23.46 住民参加・手続き重視型
     国見町    13      11.71   52     46.85 住民参加・手続き重視型
     吉見町    16      11.68   57     41.61 住民参加・手続き重視型
     新得町    12      11.54   37     35.58 住民参加・手続き重視型
     浜中町    19      11.31   44     26.19 住民参加・手続き重視型
     松崎町    12      11.21   33     30.84 住民参加・手続き重視型
    南島原市    36      11.18   82     25.47 住民参加・手続き重視型
     金沢市    11      11.00   46     46.00 住民参加・手続き重視型
     奈義町     7      10.94   33     51.56 住民参加・手続き重視型
    北茨城市     6      10.91   24     43.64 住民参加・手続き重視型
     鏡野町     6      10.91   43     78.18 住民参加・手続き重視型
     西脇市    11      10.89   52     51.49 住民参加・手続き重視型
     嬉野市    21      10.88   90     46.63 住民参加・手続き重視型
  茨城県守谷市     7      10.77   40     61.54 住民参加・手続き重視型
    ニセコ町    12      10.62   51     45.13 住民参加・手続き重視型
     高槻市    11      10.58   47     45.19 住民参加・手続き重視型
      綾町    13      10.48   37     29.84 住民参加・手続き重視型
     結城市    12      10.43   81     70.43 住民参加・手続き重視型
     三木市     6      10.34   34     58.62 住民参加・手続き重視型
     浜松市     6      10.34   31     53.45 住民参加・手続き重視型
     生坂村    13      10.24   29     22.83 住民参加・手続き重視型
 西桂町_改正前    10      10.20   16     16.33 住民参加・手続き重視型
   かつらぎ町    10      10.20   38     38.78 住民参加・手続き重視型
     箕面市    12      10.17    8      6.78     住民参加重視型
    みどり市    23      10.13   57     25.11 住民参加・手続き重視型
     山元町     9      10.11   41     46.07 住民参加・手続き重視型
  千葉県長柄町     3      10.00   11     36.67 住民参加・手続き重視型
     能勢町    16      10.00   56     35.00 住民参加・手続き重視型
     大桑村    15       9.93   29     19.21      手続き重視型
     足利市    23       9.66   80     33.61      手続き重視型
     多可町    19       9.64   58     29.44      手続き重視型
     楢葉町    26       9.63   65     24.07      手続き重視型
     可児市    16       9.58   73     43.71      手続き重視型
     日高市     9       9.38   23     23.96      手続き重視型
     日出町    13       9.22   54     38.30      手続き重視型
     辰野町     8       9.20   26     29.89      手続き重視型
    みやこ町     8       9.09   44     50.00      手続き重視型
     田川市     5       9.09   18     32.73      手続き重視型
     宿毛市     2       9.09    4     18.18      手続き重視型
     竹田市     2       9.09    8     36.36      手続き重視型
     鶴居村    10       9.09   34     30.91      手続き重視型
    八千代町    12       9.02   71     53.38      手続き重視型
     新富町     5       8.93   25     44.64      手続き重視型
    京丹後市     5       8.93   35     62.50      手続き重視型
     矢吹町    34       8.81   72     18.65      手続き重視型
     古平町     9       8.74   42     40.78      手続き重視型
     北杜市     9       8.74   27     26.21      手続き重視型
     野木町    11       8.73   71     56.35      手続き重視型
     飯豊町     4       8.70   17     36.96      手続き重視型
    八幡平市    12       8.57   41     29.29      手続き重視型
     御宿町    10       8.47   33     27.97      手続き重視型
     和気町    15       8.38   96     53.63      手続き重視型
     島田市     5       8.33   36     60.00      手続き重視型
     笠間市     7       8.33   46     54.76      手続き重視型
 桐生市_改正前    16       8.21   32     16.41      手続き重視型
     益子町    16       8.21   76     38.97      手続き重視型
     日立市    10       8.20   52     42.62      手続き重視型
     福島市    19       8.12   85     36.32      手続き重視型
  長野県松川村    13       7.98   66     40.49      手続き重視型
     真岡市    12       7.89   72     47.37      手続き重視型
     那珂市     9       7.89   54     47.37      手続き重視型
     羅臼町     6       7.89   21     27.63      手続き重視型
     下田市     9       7.69   34     29.06      手続き重視型
     伊東市     9       7.69   19     16.24      手続き重視型
     宍粟市    11       7.53   46     31.51      手続き重視型
     天理市    25       7.42   54     16.02      手続き重視型
     赤磐市     6       7.41   34     41.98      手続き重視型
     北斗市     9       7.26   59     47.58      手続き重視型
     丹波市     7       7.22   68     70.10      手続き重視型
     市川町     6       7.06   49     57.65      手続き重視型
     川俣町     4       6.90   29     50.00      手続き重視型
     掛川市     8       6.72   38     31.93      手続き重視型
     御嵩町     4       6.67   29     48.33      手続き重視型
     函南町     4       6.56   29     47.54      手続き重視型
     神戸市    10       6.54   72     47.06      手続き重視型
     岩国市     8       6.50   45     36.59      手続き重視型
     大子町     5       6.49   34     44.16      手続き重視型
     仙台市    18       6.47   59     21.22      手続き重視型
     磐田市     5       6.25   29     36.25      手続き重視型
     米原市    23       6.12   62     16.49      手続き重視型
     沼津市     9       6.00   39     26.00      手続き重視型
    中津川市     7       5.88   44     36.97      手続き重視型
     松田町     8       5.84   47     34.31      手続き重視型
     羽幌町    18       5.71   31      9.84         標準型
茨城県常陸太田市     5       5.43   48     52.17      手続き重視型
     美里町     8       5.26   60     39.47      手続き重視型
    富士宮市     4       5.26   18     23.68      手続き重視型
     備前市     7       5.19   57     42.22      手続き重視型
     菊川市     5       5.15   29     29.90      手続き重視型
     日高町     6       5.08   48     40.68      手続き重視型
 かすみがうら市     6       4.88   38     30.89      手続き重視型
     武雄市     5       4.85   39     37.86      手続き重視型
    湯河原町     8       4.65   52     30.23      手続き重視型
     宮古市    12       4.49   51     19.10      手続き重視型
     袋井市    14       4.49   73     23.40      手続き重視型
   那須塩原市     6       4.35   31     22.46      手続き重視型
    木津川市     4       4.00   33     33.00      手続き重視型
     伊豆市     5       3.94   34     26.77      手続き重視型
     裾野市     3       3.37   21     23.60      手続き重視型
     愛南町     3       3.37   29     32.58      手続き重視型
     熱海市     4       3.23   40     32.26      手続き重視型
     日置市     3       2.78   37     34.26      手続き重視型
     宇佐市     2       2.53   38     48.10      手続き重視型
    八幡浜市     2       1.44   55     39.57      手続き重視型
     江差町     1       0.89   44     39.29      手続き重視型
   土佐清水市     0       0.00   10     12.82         標準型
     西郷村     0       0.00    7     16.28      手続き重視型


プロセス重視度の分布:
プロセス重視度
住民参加・手続き重視型    235
手続き重視型          77
標準型              2
住民参加重視型          1
Name: count, dtype: int64

## 6. 総合的な分類結果の統合

これまでの4つの観点を統合し、各自治体の条例特性を一覧表示します。

In [13]:
# 住民同意フラグの付与 (セル16の後)
# '*CLAUSE_STAKEHOLDER_CONFIRMATION' が1以上なら '有'、それ以外(0/NaN)は '無'
consent_col = '*CLAUSE_STAKEHOLDER_CONFIRMATION'
if consent_col in df_with_residuals.columns:
    df_with_residuals['住民同意'] = (
        df_with_residuals[consent_col].fillna(0).astype(float).apply(lambda x: '有' if x >= 1 else '無')
    )
else:
    df_with_residuals['住民同意'] = '無'

print('住民同意カラムを付与しました。')

住民同意カラムを付与しました。

In [14]:
# 総合結果の統合
comprehensive_result = df_with_residuals[['Municiparity_name',
                                 'ケース数',
                                 '規制タイプ',
                                 '区域類型',
                                 '住民同意',
                                 '禁止区域比率',
                                 'プロセス重視度',
                                 '住民参加スコア(正規化)',
                                 '手続きスコア(正規化)']].copy()

comprehensive_result.columns = ['自治体', 'ケース数', '規制タイプ', '区域類型', 
                                '住民同意', '禁止区域比率', 'プロセス重視度', 
                                '住民参加(正規化)', '手続き(正規化)']

# 数値を小数点第1位まで表示
for col in ['禁止区域比率', '住民参加(正規化)', '手続き(正規化)']:
    comprehensive_result[col] = comprehensive_result[col].round(1)

print("=" * 170)
print("太陽光発電規制条例の総合分類結果")
print("=" * 170)
print(comprehensive_result.to_string(index=False))

# 分類結果をCSVで保存（/home/ubuntu/cur/isep/versioning を使用）
from pathlib import Path
from versioning.filename import make_dated_versioned_path

base_name = 'Classification_munic'
output_dir = Path('/home/ubuntu/cur/isep')
output_path = make_dated_versioned_path(output_dir, f'{base_name}_', '.csv')
comprehensive_result.to_csv(output_path, index=False, encoding='utf-8-sig')
print(f"分類結果を保存しました: {output_path}")

==========================================================================================================================================================================
太陽光発電規制条例の総合分類結果
==========================================================================================================================================================================
     自治体  ケース数 規制タイプ        区域類型 住民同意  禁止区域比率     プロセス重視度  住民参加(正規化)  手続き(正規化)
    えりも町   143 届出制優位      区域設定なし    有     0.0 住民参加・手続き重視型       15.4      30.1
 かすみがうら市   123 届出制優位      区域設定なし    無     0.0      手続き重視型        4.9      30.9
   かつらぎ町    98 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       10.2      38.8
    さくら市   162 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       11.7      23.5
    つくば市   177 届出制優位 2層構造(抑制+禁止)    無     0.5 住民参加・手続き重視型       20.9      38.4
   ときがわ町   144 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       16.0      50.0
    みどり市   227 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       10.1      25.1
   みなかみ町   127 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       14.2      47.2
    みやこ町    88 届出制優位      区域設定なし    無     0.0      手続き重視型        9.1      50.0
    ニセコ町   113 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       10.6      45.1
     阿智村   117 許可制優位 2層構造(抑制+禁止)    有     0.2 住民参加・手続き重視型       17.1      49.6
     愛南町    89 許可制優位      区域設定なし    有     0.0      手続き重視型        3.4      32.6
  愛媛県上島町    72 許可制優位      区域設定なし    無     0.0 住民参加・手続き重視型       15.3      41.7
      綾町   124 許可制優位 2層構造(抑制+禁止)    無     0.3 住民参加・手続き重視型       10.5      29.8
     安中市    76 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       22.4      39.5
    安曇野市   158 許可制優位 2層構造(抑制+禁止)    有     0.3 住民参加・手続き重視型       20.3      28.5
     安平町    97 届出制優位       禁止地区制    無     1.0 住民参加・手続き重視型       17.5      32.0
     伊達市   129 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       16.3      41.1
     伊東市   117 許可制優位       抑制地区制    無     0.0      手続き重視型        7.7      16.2
   伊豆の国市    57 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       12.3      45.6
     伊豆市   127 許可制優位       抑制地区制    無     0.0      手続き重視型        3.9      26.8
     伊那市    74 許可制優位       禁止地区制    有     0.2 住民参加・手続き重視型       27.0      35.1
     伊方町    89 許可制優位       禁止地区制    無     0.4 住民参加・手続き重視型       18.0      40.4
    伊万里市    60 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       16.7      41.7
  茨城県守谷市    65 届出制優位  区域設定あり(少数)    無     0.0 住民参加・手続き重視型       10.8      61.5
茨城県常陸太田市    92 届出制優位 2層構造(抑制+禁止)    無     0.1      手続き重視型        5.4      52.2
     茨城町    66 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       15.2      53.0
     宇佐市    79 届出制優位       抑制地区制    無     0.0      手続き重視型        2.5      48.1
     宇治市    66 許可制優位       禁止地区制    無     0.8 住民参加・手続き重視型       22.7      53.0
     宇陀市   109 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       11.9      56.0
    宇都宮市   214 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       12.1      36.0
    宇和島市   263 許可制優位       禁止地区制    無     0.8 住民参加・手続き重視型       19.0      33.1
     羽幌町   315 届出制優位      区域設定なし    無     0.0         標準型        5.7       9.8
     益子町   195 届出制優位       抑制地区制    無     0.0      手続き重視型        8.2      39.0
     越生町   184 届出制優位       禁止地区制    有     1.0 住民参加・手続き重視型       16.8      46.2
     遠野市   106 許可制優位  区域設定あり(少数)    無     0.0 住民参加・手続き重視型       14.2      45.3
     塩尻市   155 届出制優位       禁止地区制    無     0.4 住民参加・手続き重視型       15.5      47.1
     塩谷町   271 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       16.6      36.5
     岡垣町    91 届出制優位 2層構造(抑制+禁止)    無     0.5 住民参加・手続き重視型       12.1      45.1
  岡山県美作市    49 届出制優位      区域設定なし    有     0.0 住民参加・手続き重視型       20.4      51.0
     下関市   159 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       11.9      31.4
     下妻市   197 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       16.2      38.1
     下田市   117 許可制優位       抑制地区制    無     0.0      手続き重視型        7.7      29.1
     加美町   152 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       24.3      34.2
     可児市   167 届出制優位       抑制地区制    無     0.0      手続き重視型        9.6      43.7
    我孫子市    39 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       15.4      41.0
     皆野町   185 許可制優位  区域設定あり(少数)    有     0.0 住民参加・手続き重視型       13.5      38.4
     角田市   114 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       19.3      43.9
     掛川市   119 許可制優位       抑制地区制    無     0.0      手続き重視型        6.7      31.9
     笠間市    84 届出制優位       抑制地区制    無     0.0      手続き重視型        8.3      54.8
     滑川町   150 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       14.0      44.7
      関市    84 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       11.9      53.6
     丸森町   141 許可制優位 2層構造(抑制+禁止)    無     0.5 住民参加・手続き重視型       17.0      55.3
     岩国市   123 届出制優位       抑制地区制    無     0.0      手続き重視型        6.5      36.6
     嬉野市   193 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       10.9      46.6
     寄居町    88 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       23.9      63.6
    紀美野町   138 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       15.2      26.8
     鬼北町   108 許可制優位       禁止地区制    有     1.0 住民参加・手続き重視型       13.9      30.6
     亀岡市    74 許可制優位       禁止地区制    無     1.0 住民参加・手続き重視型       23.0      55.4
     菊川市    97 許可制優位       抑制地区制    無     0.0      手続き重視型        5.2      29.9
     菊池市   237 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       19.4      32.9
     吉岡町   100 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       19.0      48.0
     吉賀町   115 許可制優位       禁止地区制    有     1.0 住民参加・手続き重視型       20.0      31.3
     吉見町   137 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       11.7      41.6
     宮古市   267 許可制優位      区域設定なし    無     0.0      手続き重視型        4.5      19.1
     牛久市   109 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       28.4      52.3
    京丹後市    56 届出制優位      区域設定なし    無     0.0      手続き重視型        8.9      62.5
    京丹波町   198 届出制優位 2層構造(抑制+禁止)    無     0.4 住民参加・手続き重視型       12.1      31.3
    京田辺市   192 許可制優位       禁止地区制    有     0.8 住民参加・手続き重視型       14.6      34.9
     喬木村    90 許可制優位 2層構造(抑制+禁止)    無     0.2 住民参加・手続き重視型       13.3      33.3
      境町    77 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       22.1      55.8
     橋本市    47 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       19.1      46.8
     鏡野町    55 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       10.9      78.2
     玉川村   103 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       15.5      38.8
     桐生市   254 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       17.3      37.8
 桐生市_改正前   195 許可制優位       抑制地区制    無     0.0      手続き重視型        8.2      16.4
      錦町   118 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       22.0      43.2
     金沢市   100 許可制優位 2層構造(抑制+禁止)    無     0.5 住民参加・手続き重視型       11.0      46.0
     串本町   129 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       16.3      29.5
     釧路市   178 許可制優位 2層構造(抑制+禁止)    無     0.5 住民参加・手続き重視型       15.2      41.6
     熊取町    57 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       22.8      54.4
     熊谷市   138 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       19.6      47.8
     栗原市    64 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       15.6      51.6
     恵那市   214 許可制優位  区域設定あり(少数)    有     0.0 住民参加・手続き重視型       15.9      33.2
     結城市   115 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       10.4      70.4
     月形町    94 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       17.0      46.8
      原村    58 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       22.4      56.9
     古河市    65 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       12.3      69.2
    古座川町   102 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       12.7      33.3
     古平町   103 許可制優位      区域設定なし    無     0.0      手続き重視型        8.7      40.8
     湖西市    76 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       26.3      48.7
     五霞町    61 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       27.9      72.1
     五條市    99 届出制優位 2層構造(抑制+禁止)    有     0.1 住民参加・手続き重視型       17.2      29.3
     御宿町   118 許可制優位       抑制地区制    無     0.0      手続き重視型        8.5      28.0
     御所市   141 届出制優位 2層構造(抑制+禁止)    無     0.2 住民参加・手続き重視型       18.4      27.7
     御嵩町    60 届出制優位      区域設定なし    無     0.0      手続き重視型        6.7      48.3
    御前崎市    83 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       12.0      27.7
     厚真町    50 届出制優位       禁止地区制    無     1.0 住民参加・手続き重視型       18.0      34.0
     江差町   112 届出制優位      区域設定なし    無     0.0      手続き重視型        0.9      39.3
     高崎市   159 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       15.7      30.8
     高山村   263 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       19.4      35.4
     高取町    61 届出制優位       禁止地区制    有     0.3 住民参加・手続き重視型       21.3      47.5
  高知県須崎市    58 許可制優位      区域設定なし    無     0.0 住民参加・手続き重視型       13.8      27.6
     高槻市   104 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       10.6      45.2
     国見町   111 許可制優位      区域設定なし    有     0.0 住民参加・手続き重視型       11.7      46.8
     今金町    81 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       22.2      39.5
    佐久穂町   141 許可制優位       禁止地区制    有     0.7 住民参加・手続き重視型       17.7      40.4
     佐伯市   102 届出制優位  区域設定あり(少数)    無     0.0 住民参加・手続き重視型       11.8      38.2
     佐野市   196 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       13.3      35.2
     坂東市    73 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       19.2      57.5
     桜井市   104 届出制優位 2層構造(抑制+禁止)    無     0.4 住民参加・手続き重視型       16.3      28.8
     三郷町    70 許可制優位       禁止地区制    有     0.2 住民参加・手続き重視型       24.3      45.7
     三木市    58 届出制優位       禁止地区制    無     1.0 住民参加・手続き重視型       10.3      58.6
     山形村   118 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       37.3      50.0
     山元町    89 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       10.1      46.1
     士別市   156 届出制優位       禁止地区制    無     1.0 住民参加・手続き重視型       12.2      41.7
     市川町    85 届出制優位 2層構造(抑制+禁止)    無     0.3      手続き重視型        7.1      57.6
     志摩市    90 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       36.7      53.3
     鹿沼市   190 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       13.2      26.3
     鹿島市   125 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       22.4      60.8
     鹿嶋市   101 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       15.8      32.7
     宍粟市   146 届出制優位       禁止地区制    無     1.0      手続き重視型        7.5      31.5
     雫石町   139 届出制優位 2層構造(抑制+禁止)    無     0.2 住民参加・手続き重視型       14.4      43.2
    七ヶ宿町    64 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       18.8      71.9
     柴田町   109 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       15.6      47.7
     斜里町    93 届出制優位       禁止地区制    無     1.0 住民参加・手続き重視型       15.1      37.6
     渋川市   119 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       17.6      39.5
     宿毛市    22 届出制優位      区域設定なし    無     0.0      手続き重視型        9.1      18.2
     女川町   106 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       17.9      49.1
     小海町   122 許可制優位 2層構造(抑制+禁止)    有     0.5 住民参加・手続き重視型       36.9      40.2
     小諸市    81 許可制優位       禁止地区制    有     0.5 住民参加・手続き重視型       29.6      39.5
     小川町   114 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       27.2      58.8
     松江市   167 許可制優位       禁止地区制    有     0.8 住民参加・手続き重視型       19.8      35.9
     松崎町   107 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       11.2      30.8
     松田町   137 許可制優位      区域設定なし    無     0.0      手続き重視型        5.8      34.3
     松本市   155 許可制優位 2層構造(抑制+禁止)    無     0.4 住民参加・手続き重視型       25.2      48.4
     沼津市   150 許可制優位       抑制地区制    無     0.0      手続き重視型        6.0      26.0
     焼津市    75 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       12.0      22.7
     上田市   137 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       24.1      56.9
   常陸大宮市   196 許可制優位 2層構造(抑制+禁止)    無     0.4 住民参加・手続き重視型       12.2      39.8
     色麻町   114 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       19.3      36.0
     信濃町    73 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       30.1      42.5
     新宮市   105 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       12.4      32.4
     新城市    72 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       13.9      58.3
     新得町   104 届出制優位       禁止地区制    無     1.0 住民参加・手続き重視型       11.5      35.6
     新富町    56 許可制優位       抑制地区制    無     0.0      手続き重視型        8.9      44.6
     真岡市   152 届出制優位       抑制地区制    無     0.0      手続き重視型        7.9      47.4
     真庭市    61 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       21.3      32.8
     神戸市   153 許可制優位       禁止地区制    無     1.0      手続き重視型        6.5      47.1
     諏訪市    38 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       23.7      50.0
     須崎市   143 許可制優位      区域設定なし    無     0.0 住民参加・手続き重視型       20.3      25.2
     瑞浪市   119 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       29.4      42.0
     裾野市    89 許可制優位       抑制地区制    無     0.0      手続き重視型        3.4      23.6
     瀬戸市    95 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       14.7      64.2
     生坂村   127 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       10.2      22.8
     西郷村    43 届出制優位      区域設定なし    無     0.0      手続き重視型        0.0      16.3
     西桂町   110 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       12.7      41.8
 西桂町_改正前    98 届出制優位  区域設定あり(少数)    無     0.0 住民参加・手続き重視型       10.2      16.3
     西予市   132 許可制優位 2層構造(抑制+禁止)    有     0.4 住民参加・手続き重視型       18.9      38.6
     西脇市   101 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       10.9      51.5
     青木村   104 届出制優位       禁止地区制    有     1.0 住民参加・手続き重視型       18.3      63.5
 静岡県西伊豆町    63 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       12.7      39.7
 静岡県東伊豆町    78 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       23.1      37.2
     石岡市    63 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       30.2      58.7
     石巻市   114 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       17.5      50.0
     赤磐市    81 届出制優位       抑制地区制    無     0.0      手続き重視型        7.4      42.0
     赤穂市   114 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       13.2      33.3
     仙台市   278 許可制優位       抑制地区制    無     0.0      手続き重視型        6.5      21.2
  千葉県長柄町    30 届出制優位  区域設定あり(少数)    無     0.0 住民参加・手続き重視型       10.0      36.7
     川崎町   202 届出制優位 2層構造(抑制+禁止)    無     0.5 住民参加・手続き重視型       15.8      40.1
     川島町   182 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       19.8      44.0
     川俣町    58 許可制優位      区域設定なし    無     0.0      手続き重視型        6.9      50.0
     前橋市   123 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       18.7      39.8
     蔵王町   159 届出制優位 2層構造(抑制+禁止)    無     0.5 住民参加・手続き重視型       18.9      64.2
     足利市   238 許可制優位       抑制地区制    無     0.0      手続き重視型        9.7      33.6
     村田町    97 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       14.4      57.7
     多可町   197 届出制優位      区域設定なし    無     0.0      手続き重視型        9.6      29.4
     太田市   194 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       12.4      28.9
     袋井市   312 許可制優位       抑制地区制    無     0.0      手続き重視型        4.5      23.4
    大宜味村    61 届出制優位  区域設定あり(少数)    無     0.0 住民参加・手続き重視型       26.2      55.7
     大玉村    57 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       14.0      42.1
     大空町   108 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       15.7      39.8
     大桑村   151 許可制優位       抑制地区制    無     0.0      手続き重視型        9.9      19.2
     大崎市   237 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       13.1      27.8
     大子町    77 許可制優位       禁止地区制    無     0.4      手続き重視型        6.5      44.2
     大洲市    96 届出制優位 2層構造(抑制+禁止)    無     0.5 住民参加・手続き重視型       25.0      63.5
     大町市   174 許可制優位 2層構造(抑制+禁止)    無     0.3 住民参加・手続き重視型       15.5      37.9
     大町町    75 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       17.3      40.0
     大津市   117 許可制優位 2層構造(抑制+禁止)    無     0.1 住民参加・手続き重視型       12.8      35.9
     大津町   138 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       19.6      43.5
    大田原市   190 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       14.2      42.6
     大府市   106 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       14.2      55.7
   大網白里市   103 届出制優位  区域設定あり(少数)    無     0.0 住民参加・手続き重視型       17.5      35.0
     辰野町    87 許可制優位       禁止地区制    無     0.7      手続き重視型        9.2      29.9
     丹波市    97 届出制優位       禁止地区制    無     0.3      手続き重視型        7.2      70.1
     竹田市    22 届出制優位      区域設定なし    無     0.0      手続き重視型        9.1      36.4
     秩父市   109 許可制優位  区域設定あり(少数)    有     0.0 住民参加・手続き重視型       18.3      50.5
     中川村   127 届出制優位       禁止地区制    無     1.0 住民参加・手続き重視型       15.7      45.7
    中津川市   119 届出制優位       抑制地区制    無     0.0      手続き重視型        5.9      37.0
     朝日村    54 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       13.0      59.3
     長沼町   134 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       23.9      44.0
  長野県松川村   163 許可制優位      区域設定なし    無     0.0      手続き重視型        8.0      40.5
  長野県筑北村   109 届出制優位       抑制地区制    有     0.0 住民参加・手続き重視型       22.9      47.7
     長野市   247 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       16.2      38.5
     鳥羽市    68 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       17.6      35.3
     鶴居村   110 届出制優位       抑制地区制    無     0.0      手続き重視型        9.1      30.9
     天草市    43 届出制優位  区域設定あり(少数)    無     0.0 住民参加・手続き重視型       14.0      48.8
     天理市   337 届出制優位 2層構造(抑制+禁止)    無     0.2      手続き重視型        7.4      16.0
     田川市    55 届出制優位       抑制地区制    無     0.0      手続き重視型        9.1      32.7
     田村市   111 届出制優位 2層構造(抑制+禁止)    有     0.1 住民参加・手続き重視型       15.3      27.0
     登米市    74 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       21.6      48.6
     登別市   138 届出制優位 2層構造(抑制+禁止)    無     0.4 住民参加・手続き重視型       14.5      35.5
     砥部町   155 許可制優位       禁止地区制    無     1.0 住民参加・手続き重視型       18.7      41.3
     土佐市   154 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       14.9      31.2
   土佐清水市    78 届出制優位      区域設定なし    無     0.0         標準型        0.0      12.8
     島田市    60 届出制優位      区域設定なし    無     0.0      手続き重視型        8.3      60.0
     東栄町    95 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       15.8      34.7
     東海村   117 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       12.0      43.6
    東広島市    65 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       16.9      64.6
    東松山市   131 届出制優位 2層構造(抑制+禁止)    無     0.6 住民参加・手続き重視型       15.3      63.4
      東村   117 届出制優位  区域設定あり(少数)    無     0.0 住民参加・手続き重視型       17.1      38.5
    湯河原町   172 許可制優位       抑制地区制    無     0.0      手続き重視型        4.7      30.2
     藤枝市    58 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       15.5      41.4
    苫小牧市   112 届出制優位       禁止地区制    無     0.8 住民参加・手続き重視型       16.1      44.6
     奈義町    64 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       10.9      51.6
     那珂市   114 届出制優位       抑制地区制    有     0.0      手続き重視型        7.9      47.4
   那須塩原市   138 届出制優位 2層構造(抑制+禁止)    無     0.3      手続き重視型        4.3      22.5
     那須町   117 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       19.7      54.7
   那智勝浦町   113 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       14.2      32.7
     内子町    60 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       15.0      51.7
     楢葉町   270 届出制優位      区域設定なし    無     0.0      手続き重視型        9.6      24.1
    南伊勢町   174 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       33.9      42.5
     南関町   112 許可制優位  区域設定あり(少数)    無     0.0 住民参加・手続き重視型       17.0      39.3
    南三陸町    33 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       24.2      54.5
    南山城村   164 許可制優位       禁止地区制    無     1.0 住民参加・手続き重視型       20.1      43.3
    南相馬市   109 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       17.4      33.0
     南丹市    66 届出制優位      区域設定なし    無     0.0 住民参加・手続き重視型       24.2      71.2
    南知多町   153 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       30.1      43.8
     南砺市   161 許可制優位       禁止地区制    有     1.0 住民参加・手続き重視型       18.0      25.5
    南島原市   322 許可制優位       抑制地区制    有     0.0 住民参加・手続き重視型       11.2      25.5
    南箕輪村   117 届出制優位       禁止地区制    有     0.2 住民参加・手続き重視型       23.1      43.6
    南木曽町    98 届出制優位       抑制地区制    無     0.0 住民参加・手続き重視型       14.3      55.1
     日光市   128 許可制優位       抑制地区制    無     0.0 住民参加・手続き重視型       17.2      53.9
     日高市    96 許可制優位      区域設定なし    無     0.0      手続き重視型        9.4      24.0
     日高町   118 届出制優位       禁止地区制    無     1.0      手続き重視型        5.1      40.7
     日出町   141 届出制優位       抑制地区制    無     0.0      手続き重視型        9.2      38.3
     日置市   108 届出制優位      区域設定なし    無     0.0      手続き重視型        2.8      34.3

## 7. 可視化: クロス集計と散布図

分類結果を可視化し、自治体間の特徴を比較します。

In [15]:
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns

# 日本語フォント設定を修正 - デフォルトフォントを使用
japanese_fonts = [
    "M+ 1c"
]
available_fonts = {font.name for font in fm.fontManager.ttflist}
for font in japanese_fonts:
    if font in available_fonts:
        plt.rcParams["font.family"] = font
        break
else:
    plt.rcParams["font.family"] = plt.rcParams.get("font.family", ["sans-serif"])
    print("Warning: No Japanese font found; text may not render correctly.")

# クロス集計: 規制タイプ × 区域類型
cross_tab1 = pd.crosstab(df_with_residuals['規制タイプ'], df_with_residuals['区域類型'])
print("規制タイプ × 区域類型のクロス集計:")
print(cross_tab1)
print("
")

SyntaxError: unterminated string literal (detected at line 22) (3054274723.py, line 22)

In [ ]:
# matplotlib のバックエンドを確認・設定
import matplotlib
print(f"Current matplotlib backend: {matplotlib.get_backend()}")

# Jupyter Notebook での画像表示を有効にする
%matplotlib inline

# 散布図: 許可 vs 届出、抑制区域 vs 禁止区域
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# 1. 許可 vs 届出
ax1 = axes[0]
scatter1 = ax1.scatter(df_with_residuals['*CLAUSE_POSITIVE_PERMISSION_CONSENT'], 
                       df_with_residuals['*PROCEDURE_NOTICE_OPERATOR'],
                       s=df_with_residuals['ケース数']/2,
                       alpha=0.6, 
                       c=range(len(df_with_residuals)), 
                       cmap='tab20')
ax1.set_xlabel('Permission (CLAUSE_POSITIVE_PERMISSION_CONSENT)', fontsize=10)
ax1.set_ylabel('Notice (PROCEDURE_NOTICE_OPERATOR)', fontsize=10)
ax1.set_title('Regulation Type: Permission vs Notice', fontsize=12, fontweight='bold')
ax1.grid(True, alpha=0.3)
# 対角線を追加
max_val = max(df_with_residuals['*CLAUSE_POSITIVE_PERMISSION_CONSENT'].max(), 
              df_with_residuals['*PROCEDURE_NOTICE_OPERATOR'].max())
ax1.plot([0, max_val], [0, max_val], 'r--', alpha=0.3, label='Equal line')
ax1.legend()

# 2. 抑制区域 vs 禁止区域
ax2 = axes[1]
scatter2 = ax2.scatter(df_with_residuals['*CLAUSE_ZONE_Lv1'], 
                       df_with_residuals['*CLAUSE_ZONE_Lv2'],
                       s=df_with_residuals['ケース数']/2,
                       alpha=0.6,
                       c=range(len(df_with_residuals)),
                       cmap='tab20')
ax2.set_xlabel('Suppression Zone (CLAUSE_ZONE_Lv1)', fontsize=10)
ax2.set_ylabel('Prohibition Zone (CLAUSE_ZONE_Lv2)', fontsize=10)
ax2.set_title('Zone Type: Suppression vs Prohibition', fontsize=12, fontweight='bold')
ax2.grid(True, alpha=0.3)

# レイアウト調整
plt.tight_layout()

# 画像ファイルとして保存
output_image_path = '/home/ubuntu/cur/isep/solar_rule_v1.1_scatter.png'
plt.savefig(output_image_path, dpi=300, bbox_inches='tight', facecolor='white')
print(f"散布図を保存しました: {output_image_path}")

# Jupyter Notebook内で画像表示
plt.show()

# 保存された画像ファイルの情報を確認
import os
if os.path.exists(output_image_path):
    file_size = os.path.getsize(output_image_path)
    print(f"保存されたファイルサイズ: {file_size:,} bytes")
else:
    print("エラー: 画像ファイルが保存されませんでした")

In [ ]:
# クロス集計表をヒートマップとして可視化・保存
fig, ax = plt.subplots(1, 1, figsize=(8, 6))

# 規制タイプ × 区域類型のヒートマップ
sns.heatmap(cross_tab1, annot=True, fmt='d', cmap='Blues', ax=ax)
ax.set_title('Regulation Type × Zone Type
(規制タイプ × 区域類型)', fontsize=12, fontweight='bold')
ax.tick_params(axis='x', rotation=45)
ax.tick_params(axis='y', rotation=0)

# レイアウト調整
plt.tight_layout()

# クロス集計ヒートマップを保存
crosstab_image_path = '/home/ubuntu/cur/isep/solar_rule_v1.1_crosstab.png'
plt.savefig(crosstab_image_path, dpi=300, bbox_inches='tight', facecolor='white')
print(f"クロス集計ヒートマップを保存しました: {crosstab_image_path}")

# Jupyter Notebook内で表示
plt.show()

# 保存された画像ファイルの情報を確認
import os
if os.path.exists(crosstab_image_path):
    file_size = os.path.getsize(crosstab_image_path)
    print(f"保存されたファイルサイズ: {file_size:,} bytes")
else:
    print("エラー: クロス集計ヒートマップが保存されませんでした")

## 8. まとめと考察

### 分析結果の要約

本分析では、53自治体の太陽光発電規制条例を以下の4つの観点から分類しました:

1. **規制タイプ**: 許可制優位・届出制優位・混合型
2. **区域類型**: 禁止地区制・抑制地区制・2層構造・区域設定なし
4. **プロセス重視度**: 住民参加重視型・手続き重視型・住民参加・手続き重視型・標準型

### 主な発見

- **規制タイプ**: 届出制優位が31自治体と最多で、許可制優位は16自治体、混合型は6自治体
- **区域設定**: 抑制地区制(16)と禁止地区制(13)がほぼ同数。区域設定なしも8自治体存在
- **住民参加**: 40自治体が「住民参加・手続き重視型」に分類され、プロセス重視の傾向が強い

### 今後の展開

- **時系列分析**: 条例制定前後での事業展開の変化を追跡
- **地理的分析**: 地域特性(地形・土地利用など)と条例内容の関連性を検討
- **コーディングルールの改善**: レポートで指摘された改善点(住民同意取得義務の追加など)を反映